/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.openapi.tables.pojos;


import com.ke.bella.openapi.db.repo.Operator;

import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * openapi模型能力点
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ModelEndpointRelDB implements Operator, Serializable {

    private static final long serialVersionUID = -730729855;

    private Long      id;
    private String    modelName;
    private String    endpoint;
    private Long      cuid;
    private String    cuName;
    private Long      muid;
    private String    muName;
    private Timestamp ctime;
    private Timestamp mtime;

    public ModelEndpointRelDB() {}

    public ModelEndpointRelDB(ModelEndpointRelDB value) {
        this.id = value.id;
        this.modelName = value.modelName;
        this.endpoint = value.endpoint;
        this.cuid = value.cuid;
        this.cuName = value.cuName;
        this.muid = value.muid;
        this.muName = value.muName;
        this.ctime = value.ctime;
        this.mtime = value.mtime;
    }

    public ModelEndpointRelDB(
        Long      id,
        String    modelName,
        String    endpoint,
        Long      cuid,
        String    cuName,
        Long      muid,
        String    muName,
        Timestamp ctime,
        Timestamp mtime
    ) {
        this.id = id;
        this.modelName = modelName;
        this.endpoint = endpoint;
        this.cuid = cuid;
        this.cuName = cuName;
        this.muid = muid;
        this.muName = muName;
        this.ctime = ctime;
        this.mtime = mtime;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getModelName() {
        return this.modelName;
    }

    public void setModelName(String modelName) {
        this.modelName = modelName;
    }

    public String getEndpoint() {
        return this.endpoint;
    }

    public void setEndpoint(String endpoint) {
        this.endpoint = endpoint;
    }

    public Long getCuid() {
        return this.cuid;
    }

    public void setCuid(Long cuid) {
        this.cuid = cuid;
    }

    public String getCuName() {
        return this.cuName;
    }

    public void setCuName(String cuName) {
        this.cuName = cuName;
    }

    public Long getMuid() {
        return this.muid;
    }

    public void setMuid(Long muid) {
        this.muid = muid;
    }

    public String getMuName() {
        return this.muName;
    }

    public void setMuName(String muName) {
        this.muName = muName;
    }

    public Timestamp getCtime() {
        return this.ctime;
    }

    public void setCtime(Timestamp ctime) {
        this.ctime = ctime;
    }

    public Timestamp getMtime() {
        return this.mtime;
    }

    public void setMtime(Timestamp mtime) {
        this.mtime = mtime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ModelEndpointRelDB (");

        sb.append(id);
        sb.append(", ").append(modelName);
        sb.append(", ").append(endpoint);
        sb.append(", ").append(cuid);
        sb.append(", ").append(cuName);
        sb.append(", ").append(muid);
        sb.append(", ").append(muName);
        sb.append(", ").append(ctime);
        sb.append(", ").append(mtime);

        sb.append(")");
        return sb.toString();
    }
}
