/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.openapi.tables.pojos;


import com.ke.bella.openapi.db.repo.Operator;

import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * openapi类目
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OpenapiCategoryDB implements Operator, Serializable {

    private static final long serialVersionUID = -1202904899;

    private Long      id;
    private String    categoryCode;
    private String    categoryName;
    private String    parentCode;
    private String    status;
    private Long      cuid;
    private String    cuName;
    private Long      muid;
    private String    muName;
    private Timestamp ctime;
    private Timestamp mtime;

    public OpenapiCategoryDB() {}

    public OpenapiCategoryDB(OpenapiCategoryDB value) {
        this.id = value.id;
        this.categoryCode = value.categoryCode;
        this.categoryName = value.categoryName;
        this.parentCode = value.parentCode;
        this.status = value.status;
        this.cuid = value.cuid;
        this.cuName = value.cuName;
        this.muid = value.muid;
        this.muName = value.muName;
        this.ctime = value.ctime;
        this.mtime = value.mtime;
    }

    public OpenapiCategoryDB(
        Long      id,
        String    categoryCode,
        String    categoryName,
        String    parentCode,
        String    status,
        Long      cuid,
        String    cuName,
        Long      muid,
        String    muName,
        Timestamp ctime,
        Timestamp mtime
    ) {
        this.id = id;
        this.categoryCode = categoryCode;
        this.categoryName = categoryName;
        this.parentCode = parentCode;
        this.status = status;
        this.cuid = cuid;
        this.cuName = cuName;
        this.muid = muid;
        this.muName = muName;
        this.ctime = ctime;
        this.mtime = mtime;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCategoryCode() {
        return this.categoryCode;
    }

    public void setCategoryCode(String categoryCode) {
        this.categoryCode = categoryCode;
    }

    public String getCategoryName() {
        return this.categoryName;
    }

    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }

    public String getParentCode() {
        return this.parentCode;
    }

    public void setParentCode(String parentCode) {
        this.parentCode = parentCode;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Long getCuid() {
        return this.cuid;
    }

    public void setCuid(Long cuid) {
        this.cuid = cuid;
    }

    public String getCuName() {
        return this.cuName;
    }

    public void setCuName(String cuName) {
        this.cuName = cuName;
    }

    public Long getMuid() {
        return this.muid;
    }

    public void setMuid(Long muid) {
        this.muid = muid;
    }

    public String getMuName() {
        return this.muName;
    }

    public void setMuName(String muName) {
        this.muName = muName;
    }

    public Timestamp getCtime() {
        return this.ctime;
    }

    public void setCtime(Timestamp ctime) {
        this.ctime = ctime;
    }

    public Timestamp getMtime() {
        return this.mtime;
    }

    public void setMtime(Timestamp mtime) {
        this.mtime = mtime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("OpenapiCategoryDB (");

        sb.append(id);
        sb.append(", ").append(categoryCode);
        sb.append(", ").append(categoryName);
        sb.append(", ").append(parentCode);
        sb.append(", ").append(status);
        sb.append(", ").append(cuid);
        sb.append(", ").append(cuName);
        sb.append(", ").append(muid);
        sb.append(", ").append(muName);
        sb.append(", ").append(ctime);
        sb.append(", ").append(mtime);

        sb.append(")");
        return sb.toString();
    }
}
