/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.openapi.tables.pojos;


import com.ke.bella.openapi.db.repo.Operator;

import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * openapi能力点
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OpenapiEndpointDB implements Operator, Serializable {

    private static final long serialVersionUID = 1290203555;

    private Long      id;
    private String    endpoint;
    private String    endpointName;
    private String    maintainerCode;
    private String    maintainerName;
    private String    status;
    private Long      cuid;
    private String    cuName;
    private Long      muid;
    private String    muName;
    private Timestamp ctime;
    private Timestamp mtime;

    public OpenapiEndpointDB() {}

    public OpenapiEndpointDB(OpenapiEndpointDB value) {
        this.id = value.id;
        this.endpoint = value.endpoint;
        this.endpointName = value.endpointName;
        this.maintainerCode = value.maintainerCode;
        this.maintainerName = value.maintainerName;
        this.status = value.status;
        this.cuid = value.cuid;
        this.cuName = value.cuName;
        this.muid = value.muid;
        this.muName = value.muName;
        this.ctime = value.ctime;
        this.mtime = value.mtime;
    }

    public OpenapiEndpointDB(
        Long      id,
        String    endpoint,
        String    endpointName,
        String    maintainerCode,
        String    maintainerName,
        String    status,
        Long      cuid,
        String    cuName,
        Long      muid,
        String    muName,
        Timestamp ctime,
        Timestamp mtime
    ) {
        this.id = id;
        this.endpoint = endpoint;
        this.endpointName = endpointName;
        this.maintainerCode = maintainerCode;
        this.maintainerName = maintainerName;
        this.status = status;
        this.cuid = cuid;
        this.cuName = cuName;
        this.muid = muid;
        this.muName = muName;
        this.ctime = ctime;
        this.mtime = mtime;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getEndpoint() {
        return this.endpoint;
    }

    public void setEndpoint(String endpoint) {
        this.endpoint = endpoint;
    }

    public String getEndpointName() {
        return this.endpointName;
    }

    public void setEndpointName(String endpointName) {
        this.endpointName = endpointName;
    }

    public String getMaintainerCode() {
        return this.maintainerCode;
    }

    public void setMaintainerCode(String maintainerCode) {
        this.maintainerCode = maintainerCode;
    }

    public String getMaintainerName() {
        return this.maintainerName;
    }

    public void setMaintainerName(String maintainerName) {
        this.maintainerName = maintainerName;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Long getCuid() {
        return this.cuid;
    }

    public void setCuid(Long cuid) {
        this.cuid = cuid;
    }

    public String getCuName() {
        return this.cuName;
    }

    public void setCuName(String cuName) {
        this.cuName = cuName;
    }

    public Long getMuid() {
        return this.muid;
    }

    public void setMuid(Long muid) {
        this.muid = muid;
    }

    public String getMuName() {
        return this.muName;
    }

    public void setMuName(String muName) {
        this.muName = muName;
    }

    public Timestamp getCtime() {
        return this.ctime;
    }

    public void setCtime(Timestamp ctime) {
        this.ctime = ctime;
    }

    public Timestamp getMtime() {
        return this.mtime;
    }

    public void setMtime(Timestamp mtime) {
        this.mtime = mtime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("OpenapiEndpointDB (");

        sb.append(id);
        sb.append(", ").append(endpoint);
        sb.append(", ").append(endpointName);
        sb.append(", ").append(maintainerCode);
        sb.append(", ").append(maintainerName);
        sb.append(", ").append(status);
        sb.append(", ").append(cuid);
        sb.append(", ").append(cuName);
        sb.append(", ").append(muid);
        sb.append(", ").append(muName);
        sb.append(", ").append(ctime);
        sb.append(", ").append(mtime);

        sb.append(")");
        return sb.toString();
    }
}
