/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.openapi.tables.pojos;


import com.ke.bella.openapi.db.repo.Operator;

import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * openapi通道
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OpenapiChannelDB implements Operator, Serializable {

    private static final long serialVersionUID = 489713832;

    private Long      id;
    private String    entityType;
    private String    entityCode;
    private String    channelCode;
    private String    status;
    private String    dataDestination;
    private String    priority;
    private String    protocol;
    private String    supplier;
    private String    url;
    private String    channelInfo;
    private String    priceInfo;
    private Long      cuid;
    private String    cuName;
    private Long      muid;
    private String    muName;
    private Timestamp ctime;
    private Timestamp mtime;

    public OpenapiChannelDB() {}

    public OpenapiChannelDB(OpenapiChannelDB value) {
        this.id = value.id;
        this.entityType = value.entityType;
        this.entityCode = value.entityCode;
        this.channelCode = value.channelCode;
        this.status = value.status;
        this.dataDestination = value.dataDestination;
        this.priority = value.priority;
        this.protocol = value.protocol;
        this.supplier = value.supplier;
        this.url = value.url;
        this.channelInfo = value.channelInfo;
        this.priceInfo = value.priceInfo;
        this.cuid = value.cuid;
        this.cuName = value.cuName;
        this.muid = value.muid;
        this.muName = value.muName;
        this.ctime = value.ctime;
        this.mtime = value.mtime;
    }

    public OpenapiChannelDB(
        Long      id,
        String    entityType,
        String    entityCode,
        String    channelCode,
        String    status,
        String    dataDestination,
        String    priority,
        String    protocol,
        String    supplier,
        String    url,
        String    channelInfo,
        String    priceInfo,
        Long      cuid,
        String    cuName,
        Long      muid,
        String    muName,
        Timestamp ctime,
        Timestamp mtime
    ) {
        this.id = id;
        this.entityType = entityType;
        this.entityCode = entityCode;
        this.channelCode = channelCode;
        this.status = status;
        this.dataDestination = dataDestination;
        this.priority = priority;
        this.protocol = protocol;
        this.supplier = supplier;
        this.url = url;
        this.channelInfo = channelInfo;
        this.priceInfo = priceInfo;
        this.cuid = cuid;
        this.cuName = cuName;
        this.muid = muid;
        this.muName = muName;
        this.ctime = ctime;
        this.mtime = mtime;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getEntityType() {
        return this.entityType;
    }

    public void setEntityType(String entityType) {
        this.entityType = entityType;
    }

    public String getEntityCode() {
        return this.entityCode;
    }

    public void setEntityCode(String entityCode) {
        this.entityCode = entityCode;
    }

    public String getChannelCode() {
        return this.channelCode;
    }

    public void setChannelCode(String channelCode) {
        this.channelCode = channelCode;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getDataDestination() {
        return this.dataDestination;
    }

    public void setDataDestination(String dataDestination) {
        this.dataDestination = dataDestination;
    }

    public String getPriority() {
        return this.priority;
    }

    public void setPriority(String priority) {
        this.priority = priority;
    }

    public String getProtocol() {
        return this.protocol;
    }

    public void setProtocol(String protocol) {
        this.protocol = protocol;
    }

    public String getSupplier() {
        return this.supplier;
    }

    public void setSupplier(String supplier) {
        this.supplier = supplier;
    }

    public String getUrl() {
        return this.url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getChannelInfo() {
        return this.channelInfo;
    }

    public void setChannelInfo(String channelInfo) {
        this.channelInfo = channelInfo;
    }

    public String getPriceInfo() {
        return this.priceInfo;
    }

    public void setPriceInfo(String priceInfo) {
        this.priceInfo = priceInfo;
    }

    public Long getCuid() {
        return this.cuid;
    }

    public void setCuid(Long cuid) {
        this.cuid = cuid;
    }

    public String getCuName() {
        return this.cuName;
    }

    public void setCuName(String cuName) {
        this.cuName = cuName;
    }

    public Long getMuid() {
        return this.muid;
    }

    public void setMuid(Long muid) {
        this.muid = muid;
    }

    public String getMuName() {
        return this.muName;
    }

    public void setMuName(String muName) {
        this.muName = muName;
    }

    public Timestamp getCtime() {
        return this.ctime;
    }

    public void setCtime(Timestamp ctime) {
        this.ctime = ctime;
    }

    public Timestamp getMtime() {
        return this.mtime;
    }

    public void setMtime(Timestamp mtime) {
        this.mtime = mtime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("OpenapiChannelDB (");

        sb.append(id);
        sb.append(", ").append(entityType);
        sb.append(", ").append(entityCode);
        sb.append(", ").append(channelCode);
        sb.append(", ").append(status);
        sb.append(", ").append(dataDestination);
        sb.append(", ").append(priority);
        sb.append(", ").append(protocol);
        sb.append(", ").append(supplier);
        sb.append(", ").append(url);
        sb.append(", ").append(channelInfo);
        sb.append(", ").append(priceInfo);
        sb.append(", ").append(cuid);
        sb.append(", ").append(cuName);
        sb.append(", ").append(muid);
        sb.append(", ").append(muName);
        sb.append(", ").append(ctime);
        sb.append(", ").append(mtime);

        sb.append(")");
        return sb.toString();
    }
}
