/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.openapi.tables.pojos;


import com.ke.bella.openapi.db.repo.Operator;

import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * openapi能力点类目
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OpenapiEndpointCategoryRelationDB implements Operator, Serializable {

    private static final long serialVersionUID = 455146555;

    private Long      id;
    private String    endpoint;
    private String    categoryCode;
    private Integer   sort;
    private Long      cuid;
    private String    cuName;
    private Long      muid;
    private String    muName;
    private Timestamp ctime;
    private Timestamp mtime;

    public OpenapiEndpointCategoryRelationDB() {}

    public OpenapiEndpointCategoryRelationDB(OpenapiEndpointCategoryRelationDB value) {
        this.id = value.id;
        this.endpoint = value.endpoint;
        this.categoryCode = value.categoryCode;
        this.sort = value.sort;
        this.cuid = value.cuid;
        this.cuName = value.cuName;
        this.muid = value.muid;
        this.muName = value.muName;
        this.ctime = value.ctime;
        this.mtime = value.mtime;
    }

    public OpenapiEndpointCategoryRelationDB(
        Long      id,
        String    endpoint,
        String    categoryCode,
        Integer   sort,
        Long      cuid,
        String    cuName,
        Long      muid,
        String    muName,
        Timestamp ctime,
        Timestamp mtime
    ) {
        this.id = id;
        this.endpoint = endpoint;
        this.categoryCode = categoryCode;
        this.sort = sort;
        this.cuid = cuid;
        this.cuName = cuName;
        this.muid = muid;
        this.muName = muName;
        this.ctime = ctime;
        this.mtime = mtime;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getEndpoint() {
        return this.endpoint;
    }

    public void setEndpoint(String endpoint) {
        this.endpoint = endpoint;
    }

    public String getCategoryCode() {
        return this.categoryCode;
    }

    public void setCategoryCode(String categoryCode) {
        this.categoryCode = categoryCode;
    }

    public Integer getSort() {
        return this.sort;
    }

    public void setSort(Integer sort) {
        this.sort = sort;
    }

    public Long getCuid() {
        return this.cuid;
    }

    public void setCuid(Long cuid) {
        this.cuid = cuid;
    }

    public String getCuName() {
        return this.cuName;
    }

    public void setCuName(String cuName) {
        this.cuName = cuName;
    }

    public Long getMuid() {
        return this.muid;
    }

    public void setMuid(Long muid) {
        this.muid = muid;
    }

    public String getMuName() {
        return this.muName;
    }

    public void setMuName(String muName) {
        this.muName = muName;
    }

    public Timestamp getCtime() {
        return this.ctime;
    }

    public void setCtime(Timestamp ctime) {
        this.ctime = ctime;
    }

    public Timestamp getMtime() {
        return this.mtime;
    }

    public void setMtime(Timestamp mtime) {
        this.mtime = mtime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("OpenapiEndpointCategoryRelationDB (");

        sb.append(id);
        sb.append(", ").append(endpoint);
        sb.append(", ").append(categoryCode);
        sb.append(", ").append(sort);
        sb.append(", ").append(cuid);
        sb.append(", ").append(cuName);
        sb.append(", ").append(muid);
        sb.append(", ").append(muName);
        sb.append(", ").append(ctime);
        sb.append(", ").append(mtime);

        sb.append(")");
        return sb.toString();
    }
}
