#-------------------------------------------------------
# Docker环境配置区域
#-------------------------------------------------------
spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:mysql}:${DB_PORT:3306}/${DB_NAME:bella_openapi}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false
    username: ${DB_USER:bella_user}
    password: ${DB_PASSWORD:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-init-sql: SET NAMES utf8mb4
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: HikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  
  redis:
    redisson:
      config: |
        singleServerConfig:
          address: "redis://${REDIS_HOST:redis}:${REDIS_PORT:6379}"
          password: "${REDIS_PASSWORD:123456}"
        codec: !<org.redisson.client.codec.StringCodec> {}

management:
  endpoints:
    web:
      exposure:
        include: 'health,info,prometheus'
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true

bella:
  session:
    cookie-name: bella_openapi_sessionId
    max-inactive-interval: 60
    cookie-max-age: -1
    cookie-domain: ${SERVER_DOMAIN:localhost}
    cookie-context-path: /
  server:
    initializer:
      enabled: true
  login:
    type: ${login.type:}
    login-page-url: ${SERVER:http://localhost}/login
  cas:
    server-url-prefix: ${cas.server:}
    server-login-url: ${cas.server.login:}
    client-host: ${SERVER:http://localhost}
    client-support: true
    client-index-url: ${SERVER:http://localhost}
  oauth:
    client-index: ${SERVER:http://localhost}
    redirect: ${SERVER:http://localhost}
    providers:
      google:
        enabled: ${google.enable:false}
        client-id: ${google.clientId:}
        client-secret: ${google.secret:}
        auth-uri: https://accounts.google.com/o/oauth2/v2/auth
        token-uri: https://oauth2.googleapis.com/token
        user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
        scope: profile email
      github:
        enabled: ${github.enable:false}
        client-id: ${github.clientId:}
        client-secret: ${github.secret:}
        scope: read:user user:email
        authUri: https://github.com/login/oauth/authorize
        tokenUri: https://github.com/login/oauth/access_token
        userInfoUri: https://api.github.com/user

# ----- 日志级别配置 Docker环境 -----
logging:
  level:
    root: INFO
    com.ke.bella.openapi: DEBUG
