/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.openapi.tables;


import com.ke.bella.openapi.DefaultSchema;
import com.ke.bella.openapi.Indexes;
import com.ke.bella.openapi.Keys;
import com.ke.bella.openapi.tables.records.ModelRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row16;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * 模型
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Model extends TableImpl<ModelRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>model</code>
     */
    public static final Model MODEL = new Model();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ModelRecord> getRecordType() {
        return ModelRecord.class;
    }

    /**
     * The column <code>model.id</code>. 主键ID
     */
    public final TableField<ModelRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "主键ID");

    /**
     * The column <code>model.model_name</code>. 模型名称
     */
    public final TableField<ModelRecord, String> MODEL_NAME = createField(DSL.name("model_name"), SQLDataType.VARCHAR(64).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "模型名称");

    /**
     * The column <code>model.document_url</code>. 文档地址
     */
    public final TableField<ModelRecord, String> DOCUMENT_URL = createField(DSL.name("document_url"), SQLDataType.VARCHAR(256).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "文档地址");

    /**
     * The column <code>model.visibility</code>. 是否公开(private/public)
     */
    public final TableField<ModelRecord, String> VISIBILITY = createField(DSL.name("visibility"), SQLDataType.VARCHAR(64).nullable(false).defaultValue(DSL.inline("private", SQLDataType.VARCHAR)), this, "是否公开(private/public)");

    /**
     * The column <code>model.owner_type</code>. 所有者类型（系统/组织/个人）
     */
    public final TableField<ModelRecord, String> OWNER_TYPE = createField(DSL.name("owner_type"), SQLDataType.VARCHAR(16).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "所有者类型（系统/组织/个人）");

    /**
     * The column <code>model.owner_code</code>. 所有者系统号
     */
    public final TableField<ModelRecord, String> OWNER_CODE = createField(DSL.name("owner_code"), SQLDataType.VARCHAR(64).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "所有者系统号");

    /**
     * The column <code>model.owner_name</code>. 所有者名称
     */
    public final TableField<ModelRecord, String> OWNER_NAME = createField(DSL.name("owner_name"), SQLDataType.VARCHAR(16).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "所有者名称");

    /**
     * The column <code>model.status</code>. 状态(active/inactive)
     */
    public final TableField<ModelRecord, String> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR(64).nullable(false).defaultValue(DSL.inline("active", SQLDataType.VARCHAR)), this, "状态(active/inactive)");

    /**
     * The column <code>model.properties</code>. 属性
     */
    public final TableField<ModelRecord, String> PROPERTIES = createField(DSL.name("properties"), SQLDataType.VARCHAR(1024).nullable(false).defaultValue(DSL.inline("{}", SQLDataType.VARCHAR)), this, "属性");

    /**
     * The column <code>model.features</code>. 特性
     */
    public final TableField<ModelRecord, String> FEATURES = createField(DSL.name("features"), SQLDataType.VARCHAR(1024).nullable(false).defaultValue(DSL.inline("{}", SQLDataType.VARCHAR)), this, "特性");

    /**
     * The column <code>model.cuid</code>. 创建人id
     */
    public final TableField<ModelRecord, Long> CUID = createField(DSL.name("cuid"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.BIGINT)), this, "创建人id");

    /**
     * The column <code>model.cu_name</code>. 创建人姓名
     */
    public final TableField<ModelRecord, String> CU_NAME = createField(DSL.name("cu_name"), SQLDataType.VARCHAR(16).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "创建人姓名");

    /**
     * The column <code>model.muid</code>. 编辑人id
     */
    public final TableField<ModelRecord, Long> MUID = createField(DSL.name("muid"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.BIGINT)), this, "编辑人id");

    /**
     * The column <code>model.mu_name</code>. 编辑人姓名
     */
    public final TableField<ModelRecord, String> MU_NAME = createField(DSL.name("mu_name"), SQLDataType.VARCHAR(16).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "编辑人姓名");

    /**
     * The column <code>model.ctime</code>.
     */
    public final TableField<ModelRecord, LocalDateTime> CTIME = createField(DSL.name("ctime"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>model.mtime</code>.
     */
    public final TableField<ModelRecord, LocalDateTime> MTIME = createField(DSL.name("mtime"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "");

    private Model(Name alias, Table<ModelRecord> aliased) {
        this(alias, aliased, null);
    }

    private Model(Name alias, Table<ModelRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("模型"), TableOptions.table());
    }

    /**
     * Create an aliased <code>model</code> table reference
     */
    public Model(String alias) {
        this(DSL.name(alias), MODEL);
    }

    /**
     * Create an aliased <code>model</code> table reference
     */
    public Model(Name alias) {
        this(alias, MODEL);
    }

    /**
     * Create a <code>model</code> table reference
     */
    public Model() {
        this(DSL.name("model"), null);
    }

    public <O extends Record> Model(Table<O> child, ForeignKey<O, ModelRecord> key) {
        super(child, key, MODEL);
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.MODEL_IDX_OWNER_NAME, Indexes.MODEL_IDX_OWNER_TYPE_CODE);
    }

    @Override
    public Identity<ModelRecord, Long> getIdentity() {
        return (Identity<ModelRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<ModelRecord> getPrimaryKey() {
        return Keys.KEY_MODEL_PRIMARY;
    }

    @Override
    public List<UniqueKey<ModelRecord>> getKeys() {
        return Arrays.<UniqueKey<ModelRecord>>asList(Keys.KEY_MODEL_PRIMARY, Keys.KEY_MODEL_UNIQ_IDX_UNI_MODEL_NAME);
    }

    @Override
    public Model as(String alias) {
        return new Model(DSL.name(alias), this);
    }

    @Override
    public Model as(Name alias) {
        return new Model(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Model rename(String name) {
        return new Model(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Model rename(Name name) {
        return new Model(name, null);
    }

    // -------------------------------------------------------------------------
    // Row16 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row16<Long, String, String, String, String, String, String, String, String, String, Long, String, Long, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row16) super.fieldsRow();
    }
}
