/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.openapi;


import com.ke.bella.openapi.tables.Category;
import com.ke.bella.openapi.tables.Channel;
import com.ke.bella.openapi.tables.Endpoint;
import com.ke.bella.openapi.tables.EndpointCategoryRel;
import com.ke.bella.openapi.tables.Model;
import com.ke.bella.openapi.tables.ModelEndpointRel;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = 1031647543;

    /**
     * The reference instance of <code></code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * openapi类目
     */
    public final Category CATEGORY = com.ke.bella.openapi.tables.Category.CATEGORY;

    /**
     * openapi通道
     */
    public final Channel CHANNEL = com.ke.bella.openapi.tables.Channel.CHANNEL;

    /**
     * openapi能力点
     */
    public final Endpoint ENDPOINT = com.ke.bella.openapi.tables.Endpoint.ENDPOINT;

    /**
     * openapi能力点类目
     */
    public final EndpointCategoryRel ENDPOINT_CATEGORY_REL = com.ke.bella.openapi.tables.EndpointCategoryRel.ENDPOINT_CATEGORY_REL;

    /**
     * openapi模型
     */
    public final Model MODEL = com.ke.bella.openapi.tables.Model.MODEL;

    /**
     * openapi模型能力点
     */
    public final ModelEndpointRel MODEL_ENDPOINT_REL = com.ke.bella.openapi.tables.ModelEndpointRel.MODEL_ENDPOINT_REL;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Category.CATEGORY,
            Channel.CHANNEL,
            Endpoint.ENDPOINT,
            EndpointCategoryRel.ENDPOINT_CATEGORY_REL,
            Model.MODEL,
            ModelEndpointRel.MODEL_ENDPOINT_REL);
    }
}
