/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.openapi;


import com.ke.bella.openapi.tables.Apikey;
import com.ke.bella.openapi.tables.ApikeyMonthCost;
import com.ke.bella.openapi.tables.ApikeyRole;
import com.ke.bella.openapi.tables.Category;
import com.ke.bella.openapi.tables.Channel;
import com.ke.bella.openapi.tables.Endpoint;
import com.ke.bella.openapi.tables.EndpointCategoryRel;
import com.ke.bella.openapi.tables.Model;
import com.ke.bella.openapi.tables.ModelAuthorizerRel;
import com.ke.bella.openapi.tables.ModelEndpointRel;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * ak
     */
    public static final Apikey APIKEY = Apikey.APIKEY;

    /**
     * ak月花费
     */
    public static final ApikeyMonthCost APIKEY_MONTH_COST = ApikeyMonthCost.APIKEY_MONTH_COST;

    /**
     * ak角色
     */
    public static final ApikeyRole APIKEY_ROLE = ApikeyRole.APIKEY_ROLE;

    /**
     * 类目
     */
    public static final Category CATEGORY = Category.CATEGORY;

    /**
     * 通道
     */
    public static final Channel CHANNEL = Channel.CHANNEL;

    /**
     * 能力点
     */
    public static final Endpoint ENDPOINT = Endpoint.ENDPOINT;

    /**
     * 能力点类目
     */
    public static final EndpointCategoryRel ENDPOINT_CATEGORY_REL = EndpointCategoryRel.ENDPOINT_CATEGORY_REL;

    /**
     * 模型
     */
    public static final Model MODEL = Model.MODEL;

    /**
     * 模型授权信息
     */
    public static final ModelAuthorizerRel MODEL_AUTHORIZER_REL = ModelAuthorizerRel.MODEL_AUTHORIZER_REL;

    /**
     * 模型能力点
     */
    public static final ModelEndpointRel MODEL_ENDPOINT_REL = ModelEndpointRel.MODEL_ENDPOINT_REL;
}
