/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.openapi;


import com.ke.bella.openapi.tables.Category;
import com.ke.bella.openapi.tables.Channel;
import com.ke.bella.openapi.tables.Endpoint;
import com.ke.bella.openapi.tables.EndpointCategoryRel;
import com.ke.bella.openapi.tables.Model;
import com.ke.bella.openapi.tables.ModelAuthorizerRel;
import com.ke.bella.openapi.tables.ModelEndpointRel;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * openapi类目
     */
    public static final Category CATEGORY = Category.CATEGORY;

    /**
     * 通道
     */
    public static final Channel CHANNEL = Channel.CHANNEL;

    /**
     * openapi能力点
     */
    public static final Endpoint ENDPOINT = Endpoint.ENDPOINT;

    /**
     * openapi能力点类目
     */
    public static final EndpointCategoryRel ENDPOINT_CATEGORY_REL = EndpointCategoryRel.ENDPOINT_CATEGORY_REL;

    /**
     * 模型
     */
    public static final Model MODEL = Model.MODEL;

    /**
     * 模型授权信息
     */
    public static final ModelAuthorizerRel MODEL_AUTHORIZER_REL = ModelAuthorizerRel.MODEL_AUTHORIZER_REL;

    /**
     * 模型能力点
     */
    public static final ModelEndpointRel MODEL_ENDPOINT_REL = ModelEndpointRel.MODEL_ENDPOINT_REL;
}
