/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.openapi.tables.records;


import com.ke.bella.openapi.db.repo.Operator;
import com.ke.bella.openapi.tables.ApikeyRole;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * ak角色
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ApikeyRoleRecord extends UpdatableRecordImpl<ApikeyRoleRecord> implements Operator, Record9<Long, String, String, Long, String, Long, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>apikey_role.id</code>. 主键ID
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>apikey_role.id</code>. 主键ID
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>apikey_role.role_code</code>. ak编码
     */
    public void setRoleCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>apikey_role.role_code</code>. ak编码
     */
    public String getRoleCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>apikey_role.path</code>. 授权的path
     */
    public void setPath(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>apikey_role.path</code>. 授权的path
     */
    public String getPath() {
        return (String) get(2);
    }

    /**
     * Setter for <code>apikey_role.cuid</code>. 创建人id
     */
    public void setCuid(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>apikey_role.cuid</code>. 创建人id
     */
    public Long getCuid() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>apikey_role.cu_name</code>. 创建人姓名
     */
    public void setCuName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>apikey_role.cu_name</code>. 创建人姓名
     */
    public String getCuName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>apikey_role.muid</code>. 编辑人id
     */
    public void setMuid(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>apikey_role.muid</code>. 编辑人id
     */
    public Long getMuid() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>apikey_role.mu_name</code>. 编辑人姓名
     */
    public void setMuName(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>apikey_role.mu_name</code>. 编辑人姓名
     */
    public String getMuName() {
        return (String) get(6);
    }

    /**
     * Setter for <code>apikey_role.ctime</code>.
     */
    public void setCtime(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>apikey_role.ctime</code>.
     */
    public LocalDateTime getCtime() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>apikey_role.mtime</code>.
     */
    public void setMtime(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>apikey_role.mtime</code>.
     */
    public LocalDateTime getMtime() {
        return (LocalDateTime) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<Long, String, String, Long, String, Long, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<Long, String, String, Long, String, Long, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return ApikeyRole.APIKEY_ROLE.ID;
    }

    @Override
    public Field<String> field2() {
        return ApikeyRole.APIKEY_ROLE.ROLE_CODE;
    }

    @Override
    public Field<String> field3() {
        return ApikeyRole.APIKEY_ROLE.PATH;
    }

    @Override
    public Field<Long> field4() {
        return ApikeyRole.APIKEY_ROLE.CUID;
    }

    @Override
    public Field<String> field5() {
        return ApikeyRole.APIKEY_ROLE.CU_NAME;
    }

    @Override
    public Field<Long> field6() {
        return ApikeyRole.APIKEY_ROLE.MUID;
    }

    @Override
    public Field<String> field7() {
        return ApikeyRole.APIKEY_ROLE.MU_NAME;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return ApikeyRole.APIKEY_ROLE.CTIME;
    }

    @Override
    public Field<LocalDateTime> field9() {
        return ApikeyRole.APIKEY_ROLE.MTIME;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getRoleCode();
    }

    @Override
    public String component3() {
        return getPath();
    }

    @Override
    public Long component4() {
        return getCuid();
    }

    @Override
    public String component5() {
        return getCuName();
    }

    @Override
    public Long component6() {
        return getMuid();
    }

    @Override
    public String component7() {
        return getMuName();
    }

    @Override
    public LocalDateTime component8() {
        return getCtime();
    }

    @Override
    public LocalDateTime component9() {
        return getMtime();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getRoleCode();
    }

    @Override
    public String value3() {
        return getPath();
    }

    @Override
    public Long value4() {
        return getCuid();
    }

    @Override
    public String value5() {
        return getCuName();
    }

    @Override
    public Long value6() {
        return getMuid();
    }

    @Override
    public String value7() {
        return getMuName();
    }

    @Override
    public LocalDateTime value8() {
        return getCtime();
    }

    @Override
    public LocalDateTime value9() {
        return getMtime();
    }

    @Override
    public ApikeyRoleRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public ApikeyRoleRecord value2(String value) {
        setRoleCode(value);
        return this;
    }

    @Override
    public ApikeyRoleRecord value3(String value) {
        setPath(value);
        return this;
    }

    @Override
    public ApikeyRoleRecord value4(Long value) {
        setCuid(value);
        return this;
    }

    @Override
    public ApikeyRoleRecord value5(String value) {
        setCuName(value);
        return this;
    }

    @Override
    public ApikeyRoleRecord value6(Long value) {
        setMuid(value);
        return this;
    }

    @Override
    public ApikeyRoleRecord value7(String value) {
        setMuName(value);
        return this;
    }

    @Override
    public ApikeyRoleRecord value8(LocalDateTime value) {
        setCtime(value);
        return this;
    }

    @Override
    public ApikeyRoleRecord value9(LocalDateTime value) {
        setMtime(value);
        return this;
    }

    @Override
    public ApikeyRoleRecord values(Long value1, String value2, String value3, Long value4, String value5, Long value6, String value7, LocalDateTime value8, LocalDateTime value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ApikeyRoleRecord
     */
    public ApikeyRoleRecord() {
        super(ApikeyRole.APIKEY_ROLE);
    }

    /**
     * Create a detached, initialised ApikeyRoleRecord
     */
    public ApikeyRoleRecord(Long id, String roleCode, String path, Long cuid, String cuName, Long muid, String muName, LocalDateTime ctime, LocalDateTime mtime) {
        super(ApikeyRole.APIKEY_ROLE);

        setId(id);
        setRoleCode(roleCode);
        setPath(path);
        setCuid(cuid);
        setCuName(cuName);
        setMuid(muid);
        setMuName(muName);
        setCtime(ctime);
        setMtime(mtime);
    }
}
