/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.openapi.tables.records;


import com.ke.bella.openapi.db.repo.Operator;
import com.ke.bella.openapi.tables.ApiKey;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record20;
import org.jooq.Row20;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * ak
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ApiKeyRecord extends UpdatableRecordImpl<ApiKeyRecord> implements Operator, Record20<Long, String, String, String, String, Long, String, String, String, String, String, Byte, BigDecimal, String, Long, String, Long, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>api_key.id</code>. 主键ID
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>api_key.id</code>. 主键ID
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>api_key.code</code>. ak编码
     */
    public void setCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>api_key.code</code>. ak编码
     */
    public String getCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>api_key.ak_sha</code>. 加密ak
     */
    public void setAkSha(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>api_key.ak_sha</code>. 加密ak
     */
    public String getAkSha() {
        return (String) get(2);
    }

    /**
     * Setter for <code>api_key.ak_display</code>. 脱敏ak
     */
    public void setAkDisplay(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>api_key.ak_display</code>. 脱敏ak
     */
    public String getAkDisplay() {
        return (String) get(3);
    }

    /**
     * Setter for <code>api_key.parent_code</code>. 父ak
     */
    public void setParentCode(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>api_key.parent_code</code>. 父ak
     */
    public String getParentCode() {
        return (String) get(4);
    }

    /**
     * Setter for <code>api_key.user_id</code>. 授权人id
     */
    public void setUserId(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>api_key.user_id</code>. 授权人id
     */
    public Long getUserId() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>api_key.owner_type</code>. 所有者类型（系统/组织/个人）
     */
    public void setOwnerType(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>api_key.owner_type</code>. 所有者类型（系统/组织/个人）
     */
    public String getOwnerType() {
        return (String) get(6);
    }

    /**
     * Setter for <code>api_key.owner_code</code>. 所有者系统号
     */
    public void setOwnerCode(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>api_key.owner_code</code>. 所有者系统号
     */
    public String getOwnerCode() {
        return (String) get(7);
    }

    /**
     * Setter for <code>api_key.owner_name</code>. 所有者名称
     */
    public void setOwnerName(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>api_key.owner_name</code>. 所有者名称
     */
    public String getOwnerName() {
        return (String) get(8);
    }

    /**
     * Setter for <code>api_key.role_code</code>. 角色编码
     */
    public void setRoleCode(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>api_key.role_code</code>. 角色编码
     */
    public String getRoleCode() {
        return (String) get(9);
    }

    /**
     * Setter for <code>api_key.certify_code</code>. 安全认证码
     */
    public void setCertifyCode(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>api_key.certify_code</code>. 安全认证码
     */
    public String getCertifyCode() {
        return (String) get(10);
    }

    /**
     * Setter for <code>api_key.safety_level</code>. 安全等级
     */
    public void setSafetyLevel(Byte value) {
        set(11, value);
    }

    /**
     * Getter for <code>api_key.safety_level</code>. 安全等级
     */
    public Byte getSafetyLevel() {
        return (Byte) get(11);
    }

    /**
     * Setter for <code>api_key.month_quota</code>. 每月额度
     */
    public void setMonthQuota(BigDecimal value) {
        set(12, value);
    }

    /**
     * Getter for <code>api_key.month_quota</code>. 每月额度
     */
    public BigDecimal getMonthQuota() {
        return (BigDecimal) get(12);
    }

    /**
     * Setter for <code>api_key.status</code>. 状态(active/inactive)
     */
    public void setStatus(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>api_key.status</code>. 状态(active/inactive)
     */
    public String getStatus() {
        return (String) get(13);
    }

    /**
     * Setter for <code>api_key.cuid</code>. 创建人id
     */
    public void setCuid(Long value) {
        set(14, value);
    }

    /**
     * Getter for <code>api_key.cuid</code>. 创建人id
     */
    public Long getCuid() {
        return (Long) get(14);
    }

    /**
     * Setter for <code>api_key.cu_name</code>. 创建人姓名
     */
    public void setCuName(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>api_key.cu_name</code>. 创建人姓名
     */
    public String getCuName() {
        return (String) get(15);
    }

    /**
     * Setter for <code>api_key.muid</code>. 编辑人id
     */
    public void setMuid(Long value) {
        set(16, value);
    }

    /**
     * Getter for <code>api_key.muid</code>. 编辑人id
     */
    public Long getMuid() {
        return (Long) get(16);
    }

    /**
     * Setter for <code>api_key.mu_name</code>. 编辑人姓名
     */
    public void setMuName(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>api_key.mu_name</code>. 编辑人姓名
     */
    public String getMuName() {
        return (String) get(17);
    }

    /**
     * Setter for <code>api_key.ctime</code>.
     */
    public void setCtime(LocalDateTime value) {
        set(18, value);
    }

    /**
     * Getter for <code>api_key.ctime</code>.
     */
    public LocalDateTime getCtime() {
        return (LocalDateTime) get(18);
    }

    /**
     * Setter for <code>api_key.mtime</code>.
     */
    public void setMtime(LocalDateTime value) {
        set(19, value);
    }

    /**
     * Getter for <code>api_key.mtime</code>.
     */
    public LocalDateTime getMtime() {
        return (LocalDateTime) get(19);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record20 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row20<Long, String, String, String, String, Long, String, String, String, String, String, Byte, BigDecimal, String, Long, String, Long, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row20) super.fieldsRow();
    }

    @Override
    public Row20<Long, String, String, String, String, Long, String, String, String, String, String, Byte, BigDecimal, String, Long, String, Long, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row20) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return ApiKey.API_KEY.ID;
    }

    @Override
    public Field<String> field2() {
        return ApiKey.API_KEY.CODE;
    }

    @Override
    public Field<String> field3() {
        return ApiKey.API_KEY.AK_SHA;
    }

    @Override
    public Field<String> field4() {
        return ApiKey.API_KEY.AK_DISPLAY;
    }

    @Override
    public Field<String> field5() {
        return ApiKey.API_KEY.PARENT_CODE;
    }

    @Override
    public Field<Long> field6() {
        return ApiKey.API_KEY.USER_ID;
    }

    @Override
    public Field<String> field7() {
        return ApiKey.API_KEY.OWNER_TYPE;
    }

    @Override
    public Field<String> field8() {
        return ApiKey.API_KEY.OWNER_CODE;
    }

    @Override
    public Field<String> field9() {
        return ApiKey.API_KEY.OWNER_NAME;
    }

    @Override
    public Field<String> field10() {
        return ApiKey.API_KEY.ROLE_CODE;
    }

    @Override
    public Field<String> field11() {
        return ApiKey.API_KEY.CERTIFY_CODE;
    }

    @Override
    public Field<Byte> field12() {
        return ApiKey.API_KEY.SAFETY_LEVEL;
    }

    @Override
    public Field<BigDecimal> field13() {
        return ApiKey.API_KEY.MONTH_QUOTA;
    }

    @Override
    public Field<String> field14() {
        return ApiKey.API_KEY.STATUS;
    }

    @Override
    public Field<Long> field15() {
        return ApiKey.API_KEY.CUID;
    }

    @Override
    public Field<String> field16() {
        return ApiKey.API_KEY.CU_NAME;
    }

    @Override
    public Field<Long> field17() {
        return ApiKey.API_KEY.MUID;
    }

    @Override
    public Field<String> field18() {
        return ApiKey.API_KEY.MU_NAME;
    }

    @Override
    public Field<LocalDateTime> field19() {
        return ApiKey.API_KEY.CTIME;
    }

    @Override
    public Field<LocalDateTime> field20() {
        return ApiKey.API_KEY.MTIME;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getCode();
    }

    @Override
    public String component3() {
        return getAkSha();
    }

    @Override
    public String component4() {
        return getAkDisplay();
    }

    @Override
    public String component5() {
        return getParentCode();
    }

    @Override
    public Long component6() {
        return getUserId();
    }

    @Override
    public String component7() {
        return getOwnerType();
    }

    @Override
    public String component8() {
        return getOwnerCode();
    }

    @Override
    public String component9() {
        return getOwnerName();
    }

    @Override
    public String component10() {
        return getRoleCode();
    }

    @Override
    public String component11() {
        return getCertifyCode();
    }

    @Override
    public Byte component12() {
        return getSafetyLevel();
    }

    @Override
    public BigDecimal component13() {
        return getMonthQuota();
    }

    @Override
    public String component14() {
        return getStatus();
    }

    @Override
    public Long component15() {
        return getCuid();
    }

    @Override
    public String component16() {
        return getCuName();
    }

    @Override
    public Long component17() {
        return getMuid();
    }

    @Override
    public String component18() {
        return getMuName();
    }

    @Override
    public LocalDateTime component19() {
        return getCtime();
    }

    @Override
    public LocalDateTime component20() {
        return getMtime();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getCode();
    }

    @Override
    public String value3() {
        return getAkSha();
    }

    @Override
    public String value4() {
        return getAkDisplay();
    }

    @Override
    public String value5() {
        return getParentCode();
    }

    @Override
    public Long value6() {
        return getUserId();
    }

    @Override
    public String value7() {
        return getOwnerType();
    }

    @Override
    public String value8() {
        return getOwnerCode();
    }

    @Override
    public String value9() {
        return getOwnerName();
    }

    @Override
    public String value10() {
        return getRoleCode();
    }

    @Override
    public String value11() {
        return getCertifyCode();
    }

    @Override
    public Byte value12() {
        return getSafetyLevel();
    }

    @Override
    public BigDecimal value13() {
        return getMonthQuota();
    }

    @Override
    public String value14() {
        return getStatus();
    }

    @Override
    public Long value15() {
        return getCuid();
    }

    @Override
    public String value16() {
        return getCuName();
    }

    @Override
    public Long value17() {
        return getMuid();
    }

    @Override
    public String value18() {
        return getMuName();
    }

    @Override
    public LocalDateTime value19() {
        return getCtime();
    }

    @Override
    public LocalDateTime value20() {
        return getMtime();
    }

    @Override
    public ApiKeyRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public ApiKeyRecord value2(String value) {
        setCode(value);
        return this;
    }

    @Override
    public ApiKeyRecord value3(String value) {
        setAkSha(value);
        return this;
    }

    @Override
    public ApiKeyRecord value4(String value) {
        setAkDisplay(value);
        return this;
    }

    @Override
    public ApiKeyRecord value5(String value) {
        setParentCode(value);
        return this;
    }

    @Override
    public ApiKeyRecord value6(Long value) {
        setUserId(value);
        return this;
    }

    @Override
    public ApiKeyRecord value7(String value) {
        setOwnerType(value);
        return this;
    }

    @Override
    public ApiKeyRecord value8(String value) {
        setOwnerCode(value);
        return this;
    }

    @Override
    public ApiKeyRecord value9(String value) {
        setOwnerName(value);
        return this;
    }

    @Override
    public ApiKeyRecord value10(String value) {
        setRoleCode(value);
        return this;
    }

    @Override
    public ApiKeyRecord value11(String value) {
        setCertifyCode(value);
        return this;
    }

    @Override
    public ApiKeyRecord value12(Byte value) {
        setSafetyLevel(value);
        return this;
    }

    @Override
    public ApiKeyRecord value13(BigDecimal value) {
        setMonthQuota(value);
        return this;
    }

    @Override
    public ApiKeyRecord value14(String value) {
        setStatus(value);
        return this;
    }

    @Override
    public ApiKeyRecord value15(Long value) {
        setCuid(value);
        return this;
    }

    @Override
    public ApiKeyRecord value16(String value) {
        setCuName(value);
        return this;
    }

    @Override
    public ApiKeyRecord value17(Long value) {
        setMuid(value);
        return this;
    }

    @Override
    public ApiKeyRecord value18(String value) {
        setMuName(value);
        return this;
    }

    @Override
    public ApiKeyRecord value19(LocalDateTime value) {
        setCtime(value);
        return this;
    }

    @Override
    public ApiKeyRecord value20(LocalDateTime value) {
        setMtime(value);
        return this;
    }

    @Override
    public ApiKeyRecord values(Long value1, String value2, String value3, String value4, String value5, Long value6, String value7, String value8, String value9, String value10, String value11, Byte value12, BigDecimal value13, String value14, Long value15, String value16, Long value17, String value18, LocalDateTime value19, LocalDateTime value20) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        value19(value19);
        value20(value20);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ApiKeyRecord
     */
    public ApiKeyRecord() {
        super(ApiKey.API_KEY);
    }

    /**
     * Create a detached, initialised ApiKeyRecord
     */
    public ApiKeyRecord(Long id, String code, String akSha, String akDisplay, String parentCode, Long userId, String ownerType, String ownerCode, String ownerName, String roleCode, String certifyCode, Byte safetyLevel, BigDecimal monthQuota, String status, Long cuid, String cuName, Long muid, String muName, LocalDateTime ctime, LocalDateTime mtime) {
        super(ApiKey.API_KEY);

        setId(id);
        setCode(code);
        setAkSha(akSha);
        setAkDisplay(akDisplay);
        setParentCode(parentCode);
        setUserId(userId);
        setOwnerType(ownerType);
        setOwnerCode(ownerCode);
        setOwnerName(ownerName);
        setRoleCode(roleCode);
        setCertifyCode(certifyCode);
        setSafetyLevel(safetyLevel);
        setMonthQuota(monthQuota);
        setStatus(status);
        setCuid(cuid);
        setCuName(cuName);
        setMuid(muid);
        setMuName(muName);
        setCtime(ctime);
        setMtime(mtime);
    }
}
