/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.openapi.tables.records;


import com.ke.bella.openapi.db.repo.Operator;
import com.ke.bella.openapi.tables.Channel;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record18;
import org.jooq.Row18;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * openapi通道
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ChannelRecord extends UpdatableRecordImpl<ChannelRecord> implements Operator, Record18<Long, String, String, String, String, String, String, String, String, String, String, String, Long, String, Long, String, Timestamp, Timestamp> {

    private static final long serialVersionUID = -1147656199;

    /**
     * Setter for <code>channel.id</code>. 主键ID
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>channel.id</code>. 主键ID
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>channel.entity_type</code>. 实体类型（endpoint/model）
     */
    public void setEntityType(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>channel.entity_type</code>. 实体类型（endpoint/model）
     */
    public String getEntityType() {
        return (String) get(1);
    }

    /**
     * Setter for <code>channel.entity_code</code>. 实体编码
     */
    public void setEntityCode(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>channel.entity_code</code>. 实体编码
     */
    public String getEntityCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>channel.channel_code</code>. 渠道编码
     */
    public void setChannelCode(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>channel.channel_code</code>. 渠道编码
     */
    public String getChannelCode() {
        return (String) get(3);
    }

    /**
     * Setter for <code>channel.status</code>. 状态状态(active/inactive)
     */
    public void setStatus(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>channel.status</code>. 状态状态(active/inactive)
     */
    public String getStatus() {
        return (String) get(4);
    }

    /**
     * Setter for <code>channel.data_destination</code>. 数据流向(inner/mainland/overseas)
     */
    public void setDataDestination(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>channel.data_destination</code>. 数据流向(inner/mainland/overseas)
     */
    public String getDataDestination() {
        return (String) get(5);
    }

    /**
     * Setter for <code>channel.priority</code>. 优先级(high/normal/low)
     */
    public void setPriority(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>channel.priority</code>. 优先级(high/normal/low)
     */
    public String getPriority() {
        return (String) get(6);
    }

    /**
     * Setter for <code>channel.protocol</code>. 协议
     */
    public void setProtocol(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>channel.protocol</code>. 协议
     */
    public String getProtocol() {
        return (String) get(7);
    }

    /**
     * Setter for <code>channel.supplier</code>. 服务商
     */
    public void setSupplier(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>channel.supplier</code>. 服务商
     */
    public String getSupplier() {
        return (String) get(8);
    }

    /**
     * Setter for <code>channel.url</code>. 请求通道的url
     */
    public void setUrl(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>channel.url</code>. 请求通道的url
     */
    public String getUrl() {
        return (String) get(9);
    }

    /**
     * Setter for <code>channel.channel_info</code>. 渠道信息
     */
    public void setChannelInfo(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>channel.channel_info</code>. 渠道信息
     */
    public String getChannelInfo() {
        return (String) get(10);
    }

    /**
     * Setter for <code>channel.price_info</code>. 单价
     */
    public void setPriceInfo(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>channel.price_info</code>. 单价
     */
    public String getPriceInfo() {
        return (String) get(11);
    }

    /**
     * Setter for <code>channel.cuid</code>. 创建人id
     */
    public void setCuid(Long value) {
        set(12, value);
    }

    /**
     * Getter for <code>channel.cuid</code>. 创建人id
     */
    public Long getCuid() {
        return (Long) get(12);
    }

    /**
     * Setter for <code>channel.cu_name</code>. 创建人姓名
     */
    public void setCuName(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>channel.cu_name</code>. 创建人姓名
     */
    public String getCuName() {
        return (String) get(13);
    }

    /**
     * Setter for <code>channel.muid</code>. 编辑人id
     */
    public void setMuid(Long value) {
        set(14, value);
    }

    /**
     * Getter for <code>channel.muid</code>. 编辑人id
     */
    public Long getMuid() {
        return (Long) get(14);
    }

    /**
     * Setter for <code>channel.mu_name</code>. 编辑人姓名
     */
    public void setMuName(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>channel.mu_name</code>. 编辑人姓名
     */
    public String getMuName() {
        return (String) get(15);
    }

    /**
     * Setter for <code>channel.ctime</code>.
     */
    public void setCtime(Timestamp value) {
        set(16, value);
    }

    /**
     * Getter for <code>channel.ctime</code>.
     */
    public Timestamp getCtime() {
        return (Timestamp) get(16);
    }

    /**
     * Setter for <code>channel.mtime</code>.
     */
    public void setMtime(Timestamp value) {
        set(17, value);
    }

    /**
     * Getter for <code>channel.mtime</code>.
     */
    public Timestamp getMtime() {
        return (Timestamp) get(17);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record18 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row18<Long, String, String, String, String, String, String, String, String, String, String, String, Long, String, Long, String, Timestamp, Timestamp> fieldsRow() {
        return (Row18) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row18<Long, String, String, String, String, String, String, String, String, String, String, String, Long, String, Long, String, Timestamp, Timestamp> valuesRow() {
        return (Row18) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Channel.CHANNEL.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Channel.CHANNEL.ENTITY_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Channel.CHANNEL.ENTITY_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Channel.CHANNEL.CHANNEL_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Channel.CHANNEL.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Channel.CHANNEL.DATA_DESTINATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Channel.CHANNEL.PRIORITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Channel.CHANNEL.PROTOCOL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return Channel.CHANNEL.SUPPLIER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return Channel.CHANNEL.URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return Channel.CHANNEL.CHANNEL_INFO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return Channel.CHANNEL.PRICE_INFO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field13() {
        return Channel.CHANNEL.CUID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field14() {
        return Channel.CHANNEL.CU_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field15() {
        return Channel.CHANNEL.MUID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field16() {
        return Channel.CHANNEL.MU_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field17() {
        return Channel.CHANNEL.CTIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field18() {
        return Channel.CHANNEL.MTIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getEntityType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getEntityCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getChannelCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getDataDestination();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getPriority();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getProtocol();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getSupplier();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getChannelInfo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component12() {
        return getPriceInfo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component13() {
        return getCuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component14() {
        return getCuName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component15() {
        return getMuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component16() {
        return getMuName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component17() {
        return getCtime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component18() {
        return getMtime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getEntityType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getEntityCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getChannelCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getDataDestination();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getPriority();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getProtocol();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getSupplier();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getChannelInfo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getPriceInfo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value13() {
        return getCuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value14() {
        return getCuName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value15() {
        return getMuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value16() {
        return getMuName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value17() {
        return getCtime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value18() {
        return getMtime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ChannelRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ChannelRecord value2(String value) {
        setEntityType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ChannelRecord value3(String value) {
        setEntityCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ChannelRecord value4(String value) {
        setChannelCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ChannelRecord value5(String value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ChannelRecord value6(String value) {
        setDataDestination(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ChannelRecord value7(String value) {
        setPriority(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ChannelRecord value8(String value) {
        setProtocol(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ChannelRecord value9(String value) {
        setSupplier(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ChannelRecord value10(String value) {
        setUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ChannelRecord value11(String value) {
        setChannelInfo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ChannelRecord value12(String value) {
        setPriceInfo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ChannelRecord value13(Long value) {
        setCuid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ChannelRecord value14(String value) {
        setCuName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ChannelRecord value15(Long value) {
        setMuid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ChannelRecord value16(String value) {
        setMuName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ChannelRecord value17(Timestamp value) {
        setCtime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ChannelRecord value18(Timestamp value) {
        setMtime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ChannelRecord values(Long value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10, String value11, String value12, Long value13, String value14, Long value15, String value16, Timestamp value17, Timestamp value18) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ChannelRecord
     */
    public ChannelRecord() {
        super(Channel.CHANNEL);
    }

    /**
     * Create a detached, initialised ChannelRecord
     */
    public ChannelRecord(Long id, String entityType, String entityCode, String channelCode, String status, String dataDestination, String priority, String protocol, String supplier, String url, String channelInfo, String priceInfo, Long cuid, String cuName, Long muid, String muName, Timestamp ctime, Timestamp mtime) {
        super(Channel.CHANNEL);

        set(0, id);
        set(1, entityType);
        set(2, entityCode);
        set(3, channelCode);
        set(4, status);
        set(5, dataDestination);
        set(6, priority);
        set(7, protocol);
        set(8, supplier);
        set(9, url);
        set(10, channelInfo);
        set(11, priceInfo);
        set(12, cuid);
        set(13, cuName);
        set(14, muid);
        set(15, muName);
        set(16, ctime);
        set(17, mtime);
    }
}
