/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.openapi.tables.records;


import com.ke.bella.openapi.db.repo.Operator;
import com.ke.bella.openapi.tables.EndpointCategoryRel;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * openapi能力点类目
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EndpointCategoryRelRecord extends UpdatableRecordImpl<EndpointCategoryRelRecord> implements Operator, Record10<Long, String, String, Integer, Long, String, Long, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>endpoint_category_rel.id</code>. 主键ID
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>endpoint_category_rel.id</code>. 主键ID
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>endpoint_category_rel.endpoint</code>. 能力点
     */
    public void setEndpoint(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>endpoint_category_rel.endpoint</code>. 能力点
     */
    public String getEndpoint() {
        return (String) get(1);
    }

    /**
     * Setter for <code>endpoint_category_rel.category_code</code>. 类目编码
     */
    public void setCategoryCode(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>endpoint_category_rel.category_code</code>. 类目编码
     */
    public String getCategoryCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>endpoint_category_rel.sort</code>. 排序
     */
    public void setSort(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>endpoint_category_rel.sort</code>. 排序
     */
    public Integer getSort() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>endpoint_category_rel.cuid</code>. 创建人id
     */
    public void setCuid(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>endpoint_category_rel.cuid</code>. 创建人id
     */
    public Long getCuid() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>endpoint_category_rel.cu_name</code>. 创建人姓名
     */
    public void setCuName(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>endpoint_category_rel.cu_name</code>. 创建人姓名
     */
    public String getCuName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>endpoint_category_rel.muid</code>. 编辑人id
     */
    public void setMuid(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>endpoint_category_rel.muid</code>. 编辑人id
     */
    public Long getMuid() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>endpoint_category_rel.mu_name</code>. 编辑人姓名
     */
    public void setMuName(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>endpoint_category_rel.mu_name</code>. 编辑人姓名
     */
    public String getMuName() {
        return (String) get(7);
    }

    /**
     * Setter for <code>endpoint_category_rel.ctime</code>.
     */
    public void setCtime(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>endpoint_category_rel.ctime</code>.
     */
    public LocalDateTime getCtime() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>endpoint_category_rel.mtime</code>.
     */
    public void setMtime(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>endpoint_category_rel.mtime</code>.
     */
    public LocalDateTime getMtime() {
        return (LocalDateTime) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<Long, String, String, Integer, Long, String, Long, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<Long, String, String, Integer, Long, String, Long, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return EndpointCategoryRel.ENDPOINT_CATEGORY_REL.ID;
    }

    @Override
    public Field<String> field2() {
        return EndpointCategoryRel.ENDPOINT_CATEGORY_REL.ENDPOINT;
    }

    @Override
    public Field<String> field3() {
        return EndpointCategoryRel.ENDPOINT_CATEGORY_REL.CATEGORY_CODE;
    }

    @Override
    public Field<Integer> field4() {
        return EndpointCategoryRel.ENDPOINT_CATEGORY_REL.SORT;
    }

    @Override
    public Field<Long> field5() {
        return EndpointCategoryRel.ENDPOINT_CATEGORY_REL.CUID;
    }

    @Override
    public Field<String> field6() {
        return EndpointCategoryRel.ENDPOINT_CATEGORY_REL.CU_NAME;
    }

    @Override
    public Field<Long> field7() {
        return EndpointCategoryRel.ENDPOINT_CATEGORY_REL.MUID;
    }

    @Override
    public Field<String> field8() {
        return EndpointCategoryRel.ENDPOINT_CATEGORY_REL.MU_NAME;
    }

    @Override
    public Field<LocalDateTime> field9() {
        return EndpointCategoryRel.ENDPOINT_CATEGORY_REL.CTIME;
    }

    @Override
    public Field<LocalDateTime> field10() {
        return EndpointCategoryRel.ENDPOINT_CATEGORY_REL.MTIME;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getEndpoint();
    }

    @Override
    public String component3() {
        return getCategoryCode();
    }

    @Override
    public Integer component4() {
        return getSort();
    }

    @Override
    public Long component5() {
        return getCuid();
    }

    @Override
    public String component6() {
        return getCuName();
    }

    @Override
    public Long component7() {
        return getMuid();
    }

    @Override
    public String component8() {
        return getMuName();
    }

    @Override
    public LocalDateTime component9() {
        return getCtime();
    }

    @Override
    public LocalDateTime component10() {
        return getMtime();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getEndpoint();
    }

    @Override
    public String value3() {
        return getCategoryCode();
    }

    @Override
    public Integer value4() {
        return getSort();
    }

    @Override
    public Long value5() {
        return getCuid();
    }

    @Override
    public String value6() {
        return getCuName();
    }

    @Override
    public Long value7() {
        return getMuid();
    }

    @Override
    public String value8() {
        return getMuName();
    }

    @Override
    public LocalDateTime value9() {
        return getCtime();
    }

    @Override
    public LocalDateTime value10() {
        return getMtime();
    }

    @Override
    public EndpointCategoryRelRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public EndpointCategoryRelRecord value2(String value) {
        setEndpoint(value);
        return this;
    }

    @Override
    public EndpointCategoryRelRecord value3(String value) {
        setCategoryCode(value);
        return this;
    }

    @Override
    public EndpointCategoryRelRecord value4(Integer value) {
        setSort(value);
        return this;
    }

    @Override
    public EndpointCategoryRelRecord value5(Long value) {
        setCuid(value);
        return this;
    }

    @Override
    public EndpointCategoryRelRecord value6(String value) {
        setCuName(value);
        return this;
    }

    @Override
    public EndpointCategoryRelRecord value7(Long value) {
        setMuid(value);
        return this;
    }

    @Override
    public EndpointCategoryRelRecord value8(String value) {
        setMuName(value);
        return this;
    }

    @Override
    public EndpointCategoryRelRecord value9(LocalDateTime value) {
        setCtime(value);
        return this;
    }

    @Override
    public EndpointCategoryRelRecord value10(LocalDateTime value) {
        setMtime(value);
        return this;
    }

    @Override
    public EndpointCategoryRelRecord values(Long value1, String value2, String value3, Integer value4, Long value5, String value6, Long value7, String value8, LocalDateTime value9, LocalDateTime value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EndpointCategoryRelRecord
     */
    public EndpointCategoryRelRecord() {
        super(EndpointCategoryRel.ENDPOINT_CATEGORY_REL);
    }

    /**
     * Create a detached, initialised EndpointCategoryRelRecord
     */
    public EndpointCategoryRelRecord(Long id, String endpoint, String categoryCode, Integer sort, Long cuid, String cuName, Long muid, String muName, LocalDateTime ctime, LocalDateTime mtime) {
        super(EndpointCategoryRel.ENDPOINT_CATEGORY_REL);

        setId(id);
        setEndpoint(endpoint);
        setCategoryCode(categoryCode);
        setSort(sort);
        setCuid(cuid);
        setCuName(cuName);
        setMuid(muid);
        setMuName(muName);
        setCtime(ctime);
        setMtime(mtime);
    }
}
