/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.openapi.tables.records;


import com.ke.bella.openapi.db.repo.Operator;
import com.ke.bella.openapi.tables.EndpointCategoryRel;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * openapi能力点类目
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EndpointCategoryRelRecord extends UpdatableRecordImpl<EndpointCategoryRelRecord> implements Operator, Record10<Long, String, String, Integer, Long, String, Long, String, Timestamp, Timestamp> {

    private static final long serialVersionUID = 409566563;

    /**
     * Setter for <code>endpoint_category_rel.id</code>. 主键ID
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>endpoint_category_rel.id</code>. 主键ID
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>endpoint_category_rel.endpoint</code>. 能力点
     */
    public void setEndpoint(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>endpoint_category_rel.endpoint</code>. 能力点
     */
    public String getEndpoint() {
        return (String) get(1);
    }

    /**
     * Setter for <code>endpoint_category_rel.category_code</code>. 类目编码
     */
    public void setCategoryCode(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>endpoint_category_rel.category_code</code>. 类目编码
     */
    public String getCategoryCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>endpoint_category_rel.sort</code>. 排序
     */
    public void setSort(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>endpoint_category_rel.sort</code>. 排序
     */
    public Integer getSort() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>endpoint_category_rel.cuid</code>. 创建人id
     */
    public void setCuid(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>endpoint_category_rel.cuid</code>. 创建人id
     */
    public Long getCuid() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>endpoint_category_rel.cu_name</code>. 创建人姓名
     */
    public void setCuName(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>endpoint_category_rel.cu_name</code>. 创建人姓名
     */
    public String getCuName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>endpoint_category_rel.muid</code>. 编辑人id
     */
    public void setMuid(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>endpoint_category_rel.muid</code>. 编辑人id
     */
    public Long getMuid() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>endpoint_category_rel.mu_name</code>. 编辑人姓名
     */
    public void setMuName(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>endpoint_category_rel.mu_name</code>. 编辑人姓名
     */
    public String getMuName() {
        return (String) get(7);
    }

    /**
     * Setter for <code>endpoint_category_rel.ctime</code>.
     */
    public void setCtime(Timestamp value) {
        set(8, value);
    }

    /**
     * Getter for <code>endpoint_category_rel.ctime</code>.
     */
    public Timestamp getCtime() {
        return (Timestamp) get(8);
    }

    /**
     * Setter for <code>endpoint_category_rel.mtime</code>.
     */
    public void setMtime(Timestamp value) {
        set(9, value);
    }

    /**
     * Getter for <code>endpoint_category_rel.mtime</code>.
     */
    public Timestamp getMtime() {
        return (Timestamp) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Long, String, String, Integer, Long, String, Long, String, Timestamp, Timestamp> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Long, String, String, Integer, Long, String, Long, String, Timestamp, Timestamp> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return EndpointCategoryRel.ENDPOINT_CATEGORY_REL.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return EndpointCategoryRel.ENDPOINT_CATEGORY_REL.ENDPOINT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return EndpointCategoryRel.ENDPOINT_CATEGORY_REL.CATEGORY_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return EndpointCategoryRel.ENDPOINT_CATEGORY_REL.SORT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return EndpointCategoryRel.ENDPOINT_CATEGORY_REL.CUID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return EndpointCategoryRel.ENDPOINT_CATEGORY_REL.CU_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field7() {
        return EndpointCategoryRel.ENDPOINT_CATEGORY_REL.MUID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return EndpointCategoryRel.ENDPOINT_CATEGORY_REL.MU_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return EndpointCategoryRel.ENDPOINT_CATEGORY_REL.CTIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field10() {
        return EndpointCategoryRel.ENDPOINT_CATEGORY_REL.MTIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getEndpoint();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getCategoryCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getSort();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component5() {
        return getCuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getCuName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component7() {
        return getMuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getMuName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component9() {
        return getCtime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component10() {
        return getMtime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getEndpoint();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getCategoryCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getSort();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getCuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getCuName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value7() {
        return getMuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getMuName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getCtime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value10() {
        return getMtime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EndpointCategoryRelRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EndpointCategoryRelRecord value2(String value) {
        setEndpoint(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EndpointCategoryRelRecord value3(String value) {
        setCategoryCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EndpointCategoryRelRecord value4(Integer value) {
        setSort(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EndpointCategoryRelRecord value5(Long value) {
        setCuid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EndpointCategoryRelRecord value6(String value) {
        setCuName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EndpointCategoryRelRecord value7(Long value) {
        setMuid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EndpointCategoryRelRecord value8(String value) {
        setMuName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EndpointCategoryRelRecord value9(Timestamp value) {
        setCtime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EndpointCategoryRelRecord value10(Timestamp value) {
        setMtime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EndpointCategoryRelRecord values(Long value1, String value2, String value3, Integer value4, Long value5, String value6, Long value7, String value8, Timestamp value9, Timestamp value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EndpointCategoryRelRecord
     */
    public EndpointCategoryRelRecord() {
        super(EndpointCategoryRel.ENDPOINT_CATEGORY_REL);
    }

    /**
     * Create a detached, initialised EndpointCategoryRelRecord
     */
    public EndpointCategoryRelRecord(Long id, String endpoint, String categoryCode, Integer sort, Long cuid, String cuName, Long muid, String muName, Timestamp ctime, Timestamp mtime) {
        super(EndpointCategoryRel.ENDPOINT_CATEGORY_REL);

        set(0, id);
        set(1, endpoint);
        set(2, categoryCode);
        set(3, sort);
        set(4, cuid);
        set(5, cuName);
        set(6, muid);
        set(7, muName);
        set(8, ctime);
        set(9, mtime);
    }
}
