/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.openapi.tables.records;


import com.ke.bella.openapi.db.repo.Operator;
import com.ke.bella.openapi.tables.Endpoint;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * openapi能力点
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EndpointRecord extends UpdatableRecordImpl<EndpointRecord> implements Operator, Record13<Long, String, String, String, String, String, String, Long, String, Long, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>endpoint.id</code>. 主键ID
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>endpoint.id</code>. 主键ID
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>endpoint.endpoint</code>. 请求path
     */
    public void setEndpoint(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>endpoint.endpoint</code>. 请求path
     */
    public String getEndpoint() {
        return (String) get(1);
    }

    /**
     * Setter for <code>endpoint.endpoint_code</code>. 能力点编码
     */
    public void setEndpointCode(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>endpoint.endpoint_code</code>. 能力点编码
     */
    public String getEndpointCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>endpoint.endpoint_name</code>. 能力点名称
     */
    public void setEndpointName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>endpoint.endpoint_name</code>. 能力点名称
     */
    public String getEndpointName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>endpoint.maintainer_code</code>. 维护人系统号
     */
    public void setMaintainerCode(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>endpoint.maintainer_code</code>. 维护人系统号
     */
    public String getMaintainerCode() {
        return (String) get(4);
    }

    /**
     * Setter for <code>endpoint.maintainer_name</code>. 维护人姓名
     */
    public void setMaintainerName(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>endpoint.maintainer_name</code>. 维护人姓名
     */
    public String getMaintainerName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>endpoint.status</code>. 状态(active/inactive)
     */
    public void setStatus(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>endpoint.status</code>. 状态(active/inactive)
     */
    public String getStatus() {
        return (String) get(6);
    }

    /**
     * Setter for <code>endpoint.cuid</code>. 创建人id
     */
    public void setCuid(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>endpoint.cuid</code>. 创建人id
     */
    public Long getCuid() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>endpoint.cu_name</code>. 创建人姓名
     */
    public void setCuName(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>endpoint.cu_name</code>. 创建人姓名
     */
    public String getCuName() {
        return (String) get(8);
    }

    /**
     * Setter for <code>endpoint.muid</code>. 编辑人id
     */
    public void setMuid(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>endpoint.muid</code>. 编辑人id
     */
    public Long getMuid() {
        return (Long) get(9);
    }

    /**
     * Setter for <code>endpoint.mu_name</code>. 编辑人姓名
     */
    public void setMuName(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>endpoint.mu_name</code>. 编辑人姓名
     */
    public String getMuName() {
        return (String) get(10);
    }

    /**
     * Setter for <code>endpoint.ctime</code>.
     */
    public void setCtime(LocalDateTime value) {
        set(11, value);
    }

    /**
     * Getter for <code>endpoint.ctime</code>.
     */
    public LocalDateTime getCtime() {
        return (LocalDateTime) get(11);
    }

    /**
     * Setter for <code>endpoint.mtime</code>.
     */
    public void setMtime(LocalDateTime value) {
        set(12, value);
    }

    /**
     * Getter for <code>endpoint.mtime</code>.
     */
    public LocalDateTime getMtime() {
        return (LocalDateTime) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row13<Long, String, String, String, String, String, String, Long, String, Long, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    @Override
    public Row13<Long, String, String, String, String, String, String, Long, String, Long, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row13) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Endpoint.ENDPOINT.ID;
    }

    @Override
    public Field<String> field2() {
        return Endpoint.ENDPOINT.ENDPOINT_;
    }

    @Override
    public Field<String> field3() {
        return Endpoint.ENDPOINT.ENDPOINT_CODE;
    }

    @Override
    public Field<String> field4() {
        return Endpoint.ENDPOINT.ENDPOINT_NAME;
    }

    @Override
    public Field<String> field5() {
        return Endpoint.ENDPOINT.MAINTAINER_CODE;
    }

    @Override
    public Field<String> field6() {
        return Endpoint.ENDPOINT.MAINTAINER_NAME;
    }

    @Override
    public Field<String> field7() {
        return Endpoint.ENDPOINT.STATUS;
    }

    @Override
    public Field<Long> field8() {
        return Endpoint.ENDPOINT.CUID;
    }

    @Override
    public Field<String> field9() {
        return Endpoint.ENDPOINT.CU_NAME;
    }

    @Override
    public Field<Long> field10() {
        return Endpoint.ENDPOINT.MUID;
    }

    @Override
    public Field<String> field11() {
        return Endpoint.ENDPOINT.MU_NAME;
    }

    @Override
    public Field<LocalDateTime> field12() {
        return Endpoint.ENDPOINT.CTIME;
    }

    @Override
    public Field<LocalDateTime> field13() {
        return Endpoint.ENDPOINT.MTIME;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getEndpoint();
    }

    @Override
    public String component3() {
        return getEndpointCode();
    }

    @Override
    public String component4() {
        return getEndpointName();
    }

    @Override
    public String component5() {
        return getMaintainerCode();
    }

    @Override
    public String component6() {
        return getMaintainerName();
    }

    @Override
    public String component7() {
        return getStatus();
    }

    @Override
    public Long component8() {
        return getCuid();
    }

    @Override
    public String component9() {
        return getCuName();
    }

    @Override
    public Long component10() {
        return getMuid();
    }

    @Override
    public String component11() {
        return getMuName();
    }

    @Override
    public LocalDateTime component12() {
        return getCtime();
    }

    @Override
    public LocalDateTime component13() {
        return getMtime();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getEndpoint();
    }

    @Override
    public String value3() {
        return getEndpointCode();
    }

    @Override
    public String value4() {
        return getEndpointName();
    }

    @Override
    public String value5() {
        return getMaintainerCode();
    }

    @Override
    public String value6() {
        return getMaintainerName();
    }

    @Override
    public String value7() {
        return getStatus();
    }

    @Override
    public Long value8() {
        return getCuid();
    }

    @Override
    public String value9() {
        return getCuName();
    }

    @Override
    public Long value10() {
        return getMuid();
    }

    @Override
    public String value11() {
        return getMuName();
    }

    @Override
    public LocalDateTime value12() {
        return getCtime();
    }

    @Override
    public LocalDateTime value13() {
        return getMtime();
    }

    @Override
    public EndpointRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public EndpointRecord value2(String value) {
        setEndpoint(value);
        return this;
    }

    @Override
    public EndpointRecord value3(String value) {
        setEndpointCode(value);
        return this;
    }

    @Override
    public EndpointRecord value4(String value) {
        setEndpointName(value);
        return this;
    }

    @Override
    public EndpointRecord value5(String value) {
        setMaintainerCode(value);
        return this;
    }

    @Override
    public EndpointRecord value6(String value) {
        setMaintainerName(value);
        return this;
    }

    @Override
    public EndpointRecord value7(String value) {
        setStatus(value);
        return this;
    }

    @Override
    public EndpointRecord value8(Long value) {
        setCuid(value);
        return this;
    }

    @Override
    public EndpointRecord value9(String value) {
        setCuName(value);
        return this;
    }

    @Override
    public EndpointRecord value10(Long value) {
        setMuid(value);
        return this;
    }

    @Override
    public EndpointRecord value11(String value) {
        setMuName(value);
        return this;
    }

    @Override
    public EndpointRecord value12(LocalDateTime value) {
        setCtime(value);
        return this;
    }

    @Override
    public EndpointRecord value13(LocalDateTime value) {
        setMtime(value);
        return this;
    }

    @Override
    public EndpointRecord values(Long value1, String value2, String value3, String value4, String value5, String value6, String value7, Long value8, String value9, Long value10, String value11, LocalDateTime value12, LocalDateTime value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EndpointRecord
     */
    public EndpointRecord() {
        super(Endpoint.ENDPOINT);
    }

    /**
     * Create a detached, initialised EndpointRecord
     */
    public EndpointRecord(Long id, String endpoint, String endpointCode, String endpointName, String maintainerCode, String maintainerName, String status, Long cuid, String cuName, Long muid, String muName, LocalDateTime ctime, LocalDateTime mtime) {
        super(Endpoint.ENDPOINT);

        setId(id);
        setEndpoint(endpoint);
        setEndpointCode(endpointCode);
        setEndpointName(endpointName);
        setMaintainerCode(maintainerCode);
        setMaintainerName(maintainerName);
        setStatus(status);
        setCuid(cuid);
        setCuName(cuName);
        setMuid(muid);
        setMuName(muName);
        setCtime(ctime);
        setMtime(mtime);
    }
}
