/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.openapi.tables.records;


import com.ke.bella.openapi.db.repo.Operator;
import com.ke.bella.openapi.tables.Model;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * openapi模型
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ModelRecord extends UpdatableRecordImpl<ModelRecord> implements Operator, Record13<Long, String, String, String, String, String, String, Long, String, Long, String, Timestamp, Timestamp> {

    private static final long serialVersionUID = -1525103346;

    /**
     * Setter for <code>model.id</code>. 主键ID
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>model.id</code>. 主键ID
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>model.model_name</code>. 模型名称
     */
    public void setModelName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>model.model_name</code>. 模型名称
     */
    public String getModelName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>model.document_url</code>. 文档地址
     */
    public void setDocumentUrl(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>model.document_url</code>. 文档地址
     */
    public String getDocumentUrl() {
        return (String) get(2);
    }

    /**
     * Setter for <code>model.visibility</code>. 是否公开(private/public)
     */
    public void setVisibility(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>model.visibility</code>. 是否公开(private/public)
     */
    public String getVisibility() {
        return (String) get(3);
    }

    /**
     * Setter for <code>model.status</code>. 状态(active/inactive)
     */
    public void setStatus(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>model.status</code>. 状态(active/inactive)
     */
    public String getStatus() {
        return (String) get(4);
    }

    /**
     * Setter for <code>model.properties</code>. 属性
     */
    public void setProperties(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>model.properties</code>. 属性
     */
    public String getProperties() {
        return (String) get(5);
    }

    /**
     * Setter for <code>model.features</code>. 特性
     */
    public void setFeatures(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>model.features</code>. 特性
     */
    public String getFeatures() {
        return (String) get(6);
    }

    /**
     * Setter for <code>model.cuid</code>. 创建人id
     */
    public void setCuid(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>model.cuid</code>. 创建人id
     */
    public Long getCuid() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>model.cu_name</code>. 创建人姓名
     */
    public void setCuName(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>model.cu_name</code>. 创建人姓名
     */
    public String getCuName() {
        return (String) get(8);
    }

    /**
     * Setter for <code>model.muid</code>. 编辑人id
     */
    public void setMuid(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>model.muid</code>. 编辑人id
     */
    public Long getMuid() {
        return (Long) get(9);
    }

    /**
     * Setter for <code>model.mu_name</code>. 编辑人姓名
     */
    public void setMuName(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>model.mu_name</code>. 编辑人姓名
     */
    public String getMuName() {
        return (String) get(10);
    }

    /**
     * Setter for <code>model.ctime</code>.
     */
    public void setCtime(Timestamp value) {
        set(11, value);
    }

    /**
     * Getter for <code>model.ctime</code>.
     */
    public Timestamp getCtime() {
        return (Timestamp) get(11);
    }

    /**
     * Setter for <code>model.mtime</code>.
     */
    public void setMtime(Timestamp value) {
        set(12, value);
    }

    /**
     * Getter for <code>model.mtime</code>.
     */
    public Timestamp getMtime() {
        return (Timestamp) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<Long, String, String, String, String, String, String, Long, String, Long, String, Timestamp, Timestamp> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<Long, String, String, String, String, String, String, Long, String, Long, String, Timestamp, Timestamp> valuesRow() {
        return (Row13) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Model.MODEL.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Model.MODEL.MODEL_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Model.MODEL.DOCUMENT_URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Model.MODEL.VISIBILITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Model.MODEL.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Model.MODEL.PROPERTIES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Model.MODEL.FEATURES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field8() {
        return Model.MODEL.CUID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return Model.MODEL.CU_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field10() {
        return Model.MODEL.MUID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return Model.MODEL.MU_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field12() {
        return Model.MODEL.CTIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field13() {
        return Model.MODEL.MTIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getModelName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getDocumentUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getVisibility();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getProperties();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getFeatures();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component8() {
        return getCuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getCuName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component10() {
        return getMuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getMuName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component12() {
        return getCtime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component13() {
        return getMtime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getModelName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getDocumentUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getVisibility();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getProperties();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getFeatures();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value8() {
        return getCuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getCuName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value10() {
        return getMuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getMuName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value12() {
        return getCtime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value13() {
        return getMtime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ModelRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ModelRecord value2(String value) {
        setModelName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ModelRecord value3(String value) {
        setDocumentUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ModelRecord value4(String value) {
        setVisibility(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ModelRecord value5(String value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ModelRecord value6(String value) {
        setProperties(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ModelRecord value7(String value) {
        setFeatures(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ModelRecord value8(Long value) {
        setCuid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ModelRecord value9(String value) {
        setCuName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ModelRecord value10(Long value) {
        setMuid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ModelRecord value11(String value) {
        setMuName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ModelRecord value12(Timestamp value) {
        setCtime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ModelRecord value13(Timestamp value) {
        setMtime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ModelRecord values(Long value1, String value2, String value3, String value4, String value5, String value6, String value7, Long value8, String value9, Long value10, String value11, Timestamp value12, Timestamp value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ModelRecord
     */
    public ModelRecord() {
        super(Model.MODEL);
    }

    /**
     * Create a detached, initialised ModelRecord
     */
    public ModelRecord(Long id, String modelName, String documentUrl, String visibility, String status, String properties, String features, Long cuid, String cuName, Long muid, String muName, Timestamp ctime, Timestamp mtime) {
        super(Model.MODEL);

        set(0, id);
        set(1, modelName);
        set(2, documentUrl);
        set(3, visibility);
        set(4, status);
        set(5, properties);
        set(6, features);
        set(7, cuid);
        set(8, cuName);
        set(9, muid);
        set(10, muName);
        set(11, ctime);
        set(12, mtime);
    }
}
