/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.openapi.tables.records;


import com.ke.bella.openapi.db.repo.Operator;
import com.ke.bella.openapi.tables.OpenapiEndpoint;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * openapi能力点
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OpenapiEndpointRecord extends UpdatableRecordImpl<OpenapiEndpointRecord> implements Operator, Record13<Long, String, String, String, String, String, String, Long, String, Long, String, Timestamp, Timestamp> {

    private static final long serialVersionUID = 1518639052;

    /**
     * Setter for <code>openapi_endpoint.id</code>. 主键ID
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>openapi_endpoint.id</code>. 主键ID
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>openapi_endpoint.endpoint</code>. 请求path
     */
    public void setEndpoint(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>openapi_endpoint.endpoint</code>. 请求path
     */
    public String getEndpoint() {
        return (String) get(1);
    }

    /**
     * Setter for <code>openapi_endpoint.endpoint_code</code>. 能力点编码
     */
    public void setEndpointCode(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>openapi_endpoint.endpoint_code</code>. 能力点编码
     */
    public String getEndpointCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>openapi_endpoint.endpoint_name</code>. 能力点名称
     */
    public void setEndpointName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>openapi_endpoint.endpoint_name</code>. 能力点名称
     */
    public String getEndpointName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>openapi_endpoint.maintainer_code</code>. 维护人系统号
     */
    public void setMaintainerCode(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>openapi_endpoint.maintainer_code</code>. 维护人系统号
     */
    public String getMaintainerCode() {
        return (String) get(4);
    }

    /**
     * Setter for <code>openapi_endpoint.maintainer_name</code>. 维护人姓名
     */
    public void setMaintainerName(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>openapi_endpoint.maintainer_name</code>. 维护人姓名
     */
    public String getMaintainerName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>openapi_endpoint.status</code>. 状态(active/inactive)
     */
    public void setStatus(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>openapi_endpoint.status</code>. 状态(active/inactive)
     */
    public String getStatus() {
        return (String) get(6);
    }

    /**
     * Setter for <code>openapi_endpoint.cuid</code>. 创建人id
     */
    public void setCuid(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>openapi_endpoint.cuid</code>. 创建人id
     */
    public Long getCuid() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>openapi_endpoint.cu_name</code>. 创建人姓名
     */
    public void setCuName(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>openapi_endpoint.cu_name</code>. 创建人姓名
     */
    public String getCuName() {
        return (String) get(8);
    }

    /**
     * Setter for <code>openapi_endpoint.muid</code>. 编辑人id
     */
    public void setMuid(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>openapi_endpoint.muid</code>. 编辑人id
     */
    public Long getMuid() {
        return (Long) get(9);
    }

    /**
     * Setter for <code>openapi_endpoint.mu_name</code>. 编辑人姓名
     */
    public void setMuName(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>openapi_endpoint.mu_name</code>. 编辑人姓名
     */
    public String getMuName() {
        return (String) get(10);
    }

    /**
     * Setter for <code>openapi_endpoint.ctime</code>.
     */
    public void setCtime(Timestamp value) {
        set(11, value);
    }

    /**
     * Getter for <code>openapi_endpoint.ctime</code>.
     */
    public Timestamp getCtime() {
        return (Timestamp) get(11);
    }

    /**
     * Setter for <code>openapi_endpoint.mtime</code>.
     */
    public void setMtime(Timestamp value) {
        set(12, value);
    }

    /**
     * Getter for <code>openapi_endpoint.mtime</code>.
     */
    public Timestamp getMtime() {
        return (Timestamp) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<Long, String, String, String, String, String, String, Long, String, Long, String, Timestamp, Timestamp> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<Long, String, String, String, String, String, String, Long, String, Long, String, Timestamp, Timestamp> valuesRow() {
        return (Row13) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return OpenapiEndpoint.OPENAPI_ENDPOINT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return OpenapiEndpoint.OPENAPI_ENDPOINT.ENDPOINT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return OpenapiEndpoint.OPENAPI_ENDPOINT.ENDPOINT_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return OpenapiEndpoint.OPENAPI_ENDPOINT.ENDPOINT_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return OpenapiEndpoint.OPENAPI_ENDPOINT.MAINTAINER_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return OpenapiEndpoint.OPENAPI_ENDPOINT.MAINTAINER_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return OpenapiEndpoint.OPENAPI_ENDPOINT.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field8() {
        return OpenapiEndpoint.OPENAPI_ENDPOINT.CUID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return OpenapiEndpoint.OPENAPI_ENDPOINT.CU_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field10() {
        return OpenapiEndpoint.OPENAPI_ENDPOINT.MUID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return OpenapiEndpoint.OPENAPI_ENDPOINT.MU_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field12() {
        return OpenapiEndpoint.OPENAPI_ENDPOINT.CTIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field13() {
        return OpenapiEndpoint.OPENAPI_ENDPOINT.MTIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getEndpoint();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getEndpointCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getEndpointName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getMaintainerCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getMaintainerName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component8() {
        return getCuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getCuName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component10() {
        return getMuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getMuName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component12() {
        return getCtime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component13() {
        return getMtime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getEndpoint();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getEndpointCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getEndpointName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getMaintainerCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getMaintainerName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value8() {
        return getCuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getCuName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value10() {
        return getMuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getMuName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value12() {
        return getCtime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value13() {
        return getMtime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OpenapiEndpointRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OpenapiEndpointRecord value2(String value) {
        setEndpoint(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OpenapiEndpointRecord value3(String value) {
        setEndpointCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OpenapiEndpointRecord value4(String value) {
        setEndpointName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OpenapiEndpointRecord value5(String value) {
        setMaintainerCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OpenapiEndpointRecord value6(String value) {
        setMaintainerName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OpenapiEndpointRecord value7(String value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OpenapiEndpointRecord value8(Long value) {
        setCuid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OpenapiEndpointRecord value9(String value) {
        setCuName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OpenapiEndpointRecord value10(Long value) {
        setMuid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OpenapiEndpointRecord value11(String value) {
        setMuName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OpenapiEndpointRecord value12(Timestamp value) {
        setCtime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OpenapiEndpointRecord value13(Timestamp value) {
        setMtime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OpenapiEndpointRecord values(Long value1, String value2, String value3, String value4, String value5, String value6, String value7, Long value8, String value9, Long value10, String value11, Timestamp value12, Timestamp value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OpenapiEndpointRecord
     */
    public OpenapiEndpointRecord() {
        super(OpenapiEndpoint.OPENAPI_ENDPOINT);
    }

    /**
     * Create a detached, initialised OpenapiEndpointRecord
     */
    public OpenapiEndpointRecord(Long id, String endpoint, String endpointCode, String endpointName, String maintainerCode, String maintainerName, String status, Long cuid, String cuName, Long muid, String muName, Timestamp ctime, Timestamp mtime) {
        super(OpenapiEndpoint.OPENAPI_ENDPOINT);

        set(0, id);
        set(1, endpoint);
        set(2, endpointCode);
        set(3, endpointName);
        set(4, maintainerCode);
        set(5, maintainerName);
        set(6, status);
        set(7, cuid);
        set(8, cuName);
        set(9, muid);
        set(10, muName);
        set(11, ctime);
        set(12, mtime);
    }
}
