/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.openapi.tables.pojos;


import com.ke.bella.openapi.db.repo.Operator;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;


/**
 * ak
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ApikeyDB implements Operator, Serializable {

    private static final long serialVersionUID = 1L;

    private Long          id;
    private String        code;
    private String        akSha;
    private String        akDisplay;
    private String        name;
    private String        parentCode;
    private String        outEntityCode;
    private String        serviceId;
    private String        ownerType;
    private String        ownerCode;
    private String        ownerName;
    private String        roleCode;
    private String        certifyCode;
    private Byte          safetyLevel;
    private BigDecimal    monthQuota;
    private String        status;
    private String        remark;
    private Long          cuid;
    private String        cuName;
    private Long          muid;
    private String        muName;
    private LocalDateTime ctime;
    private LocalDateTime mtime;

    public ApikeyDB() {}

    public ApikeyDB(ApikeyDB value) {
        this.id = value.id;
        this.code = value.code;
        this.akSha = value.akSha;
        this.akDisplay = value.akDisplay;
        this.name = value.name;
        this.parentCode = value.parentCode;
        this.outEntityCode = value.outEntityCode;
        this.serviceId = value.serviceId;
        this.ownerType = value.ownerType;
        this.ownerCode = value.ownerCode;
        this.ownerName = value.ownerName;
        this.roleCode = value.roleCode;
        this.certifyCode = value.certifyCode;
        this.safetyLevel = value.safetyLevel;
        this.monthQuota = value.monthQuota;
        this.status = value.status;
        this.remark = value.remark;
        this.cuid = value.cuid;
        this.cuName = value.cuName;
        this.muid = value.muid;
        this.muName = value.muName;
        this.ctime = value.ctime;
        this.mtime = value.mtime;
    }

    public ApikeyDB(
        Long          id,
        String        code,
        String        akSha,
        String        akDisplay,
        String        name,
        String        parentCode,
        String        outEntityCode,
        String        serviceId,
        String        ownerType,
        String        ownerCode,
        String        ownerName,
        String        roleCode,
        String        certifyCode,
        Byte          safetyLevel,
        BigDecimal    monthQuota,
        String        status,
        String        remark,
        Long          cuid,
        String        cuName,
        Long          muid,
        String        muName,
        LocalDateTime ctime,
        LocalDateTime mtime
    ) {
        this.id = id;
        this.code = code;
        this.akSha = akSha;
        this.akDisplay = akDisplay;
        this.name = name;
        this.parentCode = parentCode;
        this.outEntityCode = outEntityCode;
        this.serviceId = serviceId;
        this.ownerType = ownerType;
        this.ownerCode = ownerCode;
        this.ownerName = ownerName;
        this.roleCode = roleCode;
        this.certifyCode = certifyCode;
        this.safetyLevel = safetyLevel;
        this.monthQuota = monthQuota;
        this.status = status;
        this.remark = remark;
        this.cuid = cuid;
        this.cuName = cuName;
        this.muid = muid;
        this.muName = muName;
        this.ctime = ctime;
        this.mtime = mtime;
    }

    /**
     * Getter for <code>apikey.id</code>. 主键ID
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>apikey.id</code>. 主键ID
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>apikey.code</code>. ak编码
     */
    public String getCode() {
        return this.code;
    }

    /**
     * Setter for <code>apikey.code</code>. ak编码
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * Getter for <code>apikey.ak_sha</code>. 加密ak
     */
    public String getAkSha() {
        return this.akSha;
    }

    /**
     * Setter for <code>apikey.ak_sha</code>. 加密ak
     */
    public void setAkSha(String akSha) {
        this.akSha = akSha;
    }

    /**
     * Getter for <code>apikey.ak_display</code>. 脱敏ak
     */
    public String getAkDisplay() {
        return this.akDisplay;
    }

    /**
     * Setter for <code>apikey.ak_display</code>. 脱敏ak
     */
    public void setAkDisplay(String akDisplay) {
        this.akDisplay = akDisplay;
    }

    /**
     * Getter for <code>apikey.name</code>. 名字
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>apikey.name</code>. 名字
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>apikey.parent_code</code>. 父ak
     */
    public String getParentCode() {
        return this.parentCode;
    }

    /**
     * Setter for <code>apikey.parent_code</code>. 父ak
     */
    public void setParentCode(String parentCode) {
        this.parentCode = parentCode;
    }

    /**
     * Getter for <code>apikey.out_entity_code</code>. 授权实体code
     */
    public String getOutEntityCode() {
        return this.outEntityCode;
    }

    /**
     * Setter for <code>apikey.out_entity_code</code>. 授权实体code
     */
    public void setOutEntityCode(String outEntityCode) {
        this.outEntityCode = outEntityCode;
    }

    /**
     * Getter for <code>apikey.service_id</code>. 服务id
     */
    public String getServiceId() {
        return this.serviceId;
    }

    /**
     * Setter for <code>apikey.service_id</code>. 服务id
     */
    public void setServiceId(String serviceId) {
        this.serviceId = serviceId;
    }

    /**
     * Getter for <code>apikey.owner_type</code>. 所有者类型（系统/组织/个人）
     */
    public String getOwnerType() {
        return this.ownerType;
    }

    /**
     * Setter for <code>apikey.owner_type</code>. 所有者类型（系统/组织/个人）
     */
    public void setOwnerType(String ownerType) {
        this.ownerType = ownerType;
    }

    /**
     * Getter for <code>apikey.owner_code</code>. 所有者系统号
     */
    public String getOwnerCode() {
        return this.ownerCode;
    }

    /**
     * Setter for <code>apikey.owner_code</code>. 所有者系统号
     */
    public void setOwnerCode(String ownerCode) {
        this.ownerCode = ownerCode;
    }

    /**
     * Getter for <code>apikey.owner_name</code>. 所有者名称
     */
    public String getOwnerName() {
        return this.ownerName;
    }

    /**
     * Setter for <code>apikey.owner_name</code>. 所有者名称
     */
    public void setOwnerName(String ownerName) {
        this.ownerName = ownerName;
    }

    /**
     * Getter for <code>apikey.role_code</code>. 角色编码
     */
    public String getRoleCode() {
        return this.roleCode;
    }

    /**
     * Setter for <code>apikey.role_code</code>. 角色编码
     */
    public void setRoleCode(String roleCode) {
        this.roleCode = roleCode;
    }

    /**
     * Getter for <code>apikey.certify_code</code>. 安全认证码
     */
    public String getCertifyCode() {
        return this.certifyCode;
    }

    /**
     * Setter for <code>apikey.certify_code</code>. 安全认证码
     */
    public void setCertifyCode(String certifyCode) {
        this.certifyCode = certifyCode;
    }

    /**
     * Getter for <code>apikey.safety_level</code>. 安全等级
     */
    public Byte getSafetyLevel() {
        return this.safetyLevel;
    }

    /**
     * Setter for <code>apikey.safety_level</code>. 安全等级
     */
    public void setSafetyLevel(Byte safetyLevel) {
        this.safetyLevel = safetyLevel;
    }

    /**
     * Getter for <code>apikey.month_quota</code>. 每月额度
     */
    public BigDecimal getMonthQuota() {
        return this.monthQuota;
    }

    /**
     * Setter for <code>apikey.month_quota</code>. 每月额度
     */
    public void setMonthQuota(BigDecimal monthQuota) {
        this.monthQuota = monthQuota;
    }

    /**
     * Getter for <code>apikey.status</code>. 状态(active/inactive)
     */
    public String getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>apikey.status</code>. 状态(active/inactive)
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * Getter for <code>apikey.remark</code>. 备注
     */
    public String getRemark() {
        return this.remark;
    }

    /**
     * Setter for <code>apikey.remark</code>. 备注
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * Getter for <code>apikey.cuid</code>. 创建人id
     */
    public Long getCuid() {
        return this.cuid;
    }

    /**
     * Setter for <code>apikey.cuid</code>. 创建人id
     */
    public void setCuid(Long cuid) {
        this.cuid = cuid;
    }

    /**
     * Getter for <code>apikey.cu_name</code>. 创建人姓名
     */
    public String getCuName() {
        return this.cuName;
    }

    /**
     * Setter for <code>apikey.cu_name</code>. 创建人姓名
     */
    public void setCuName(String cuName) {
        this.cuName = cuName;
    }

    /**
     * Getter for <code>apikey.muid</code>. 编辑人id
     */
    public Long getMuid() {
        return this.muid;
    }

    /**
     * Setter for <code>apikey.muid</code>. 编辑人id
     */
    public void setMuid(Long muid) {
        this.muid = muid;
    }

    /**
     * Getter for <code>apikey.mu_name</code>. 编辑人姓名
     */
    public String getMuName() {
        return this.muName;
    }

    /**
     * Setter for <code>apikey.mu_name</code>. 编辑人姓名
     */
    public void setMuName(String muName) {
        this.muName = muName;
    }

    /**
     * Getter for <code>apikey.ctime</code>.
     */
    public LocalDateTime getCtime() {
        return this.ctime;
    }

    /**
     * Setter for <code>apikey.ctime</code>.
     */
    public void setCtime(LocalDateTime ctime) {
        this.ctime = ctime;
    }

    /**
     * Getter for <code>apikey.mtime</code>.
     */
    public LocalDateTime getMtime() {
        return this.mtime;
    }

    /**
     * Setter for <code>apikey.mtime</code>.
     */
    public void setMtime(LocalDateTime mtime) {
        this.mtime = mtime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ApikeyDB (");

        sb.append(id);
        sb.append(", ").append(code);
        sb.append(", ").append(akSha);
        sb.append(", ").append(akDisplay);
        sb.append(", ").append(name);
        sb.append(", ").append(parentCode);
        sb.append(", ").append(outEntityCode);
        sb.append(", ").append(serviceId);
        sb.append(", ").append(ownerType);
        sb.append(", ").append(ownerCode);
        sb.append(", ").append(ownerName);
        sb.append(", ").append(roleCode);
        sb.append(", ").append(certifyCode);
        sb.append(", ").append(safetyLevel);
        sb.append(", ").append(monthQuota);
        sb.append(", ").append(status);
        sb.append(", ").append(remark);
        sb.append(", ").append(cuid);
        sb.append(", ").append(cuName);
        sb.append(", ").append(muid);
        sb.append(", ").append(muName);
        sb.append(", ").append(ctime);
        sb.append(", ").append(mtime);

        sb.append(")");
        return sb.toString();
    }
}
