/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.openapi.tables.pojos;


import com.ke.bella.openapi.db.repo.Timed;

import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * 空间表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SpaceDB implements Timed, Serializable {

    private static final long serialVersionUID = 1L;

    private Long          id;
    private String        spaceCode;
    private String        spaceName;
    private String        spaceDescription;
    private Byte          status;
    private LocalDateTime ctime;
    private LocalDateTime mtime;
    private String        ownerUid;
    private Long          cuid;
    private Long          muid;

    public SpaceDB() {}

    public SpaceDB(SpaceDB value) {
        this.id = value.id;
        this.spaceCode = value.spaceCode;
        this.spaceName = value.spaceName;
        this.spaceDescription = value.spaceDescription;
        this.status = value.status;
        this.ctime = value.ctime;
        this.mtime = value.mtime;
        this.ownerUid = value.ownerUid;
        this.cuid = value.cuid;
        this.muid = value.muid;
    }

    public SpaceDB(
        Long          id,
        String        spaceCode,
        String        spaceName,
        String        spaceDescription,
        Byte          status,
        LocalDateTime ctime,
        LocalDateTime mtime,
        String        ownerUid,
        Long          cuid,
        Long          muid
    ) {
        this.id = id;
        this.spaceCode = spaceCode;
        this.spaceName = spaceName;
        this.spaceDescription = spaceDescription;
        this.status = status;
        this.ctime = ctime;
        this.mtime = mtime;
        this.ownerUid = ownerUid;
        this.cuid = cuid;
        this.muid = muid;
    }

    /**
     * Getter for <code>space.id</code>. 主键
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>space.id</code>. 主键
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>space.space_code</code>. 空间编码
     */
    public String getSpaceCode() {
        return this.spaceCode;
    }

    /**
     * Setter for <code>space.space_code</code>. 空间编码
     */
    public void setSpaceCode(String spaceCode) {
        this.spaceCode = spaceCode;
    }

    /**
     * Getter for <code>space.space_name</code>. 空间名称
     */
    public String getSpaceName() {
        return this.spaceName;
    }

    /**
     * Setter for <code>space.space_name</code>. 空间名称
     */
    public void setSpaceName(String spaceName) {
        this.spaceName = spaceName;
    }

    /**
     * Getter for <code>space.space_description</code>. 空间描述
     */
    public String getSpaceDescription() {
        return this.spaceDescription;
    }

    /**
     * Setter for <code>space.space_description</code>. 空间描述
     */
    public void setSpaceDescription(String spaceDescription) {
        this.spaceDescription = spaceDescription;
    }

    /**
     * Getter for <code>space.status</code>. 删除状态(0未删除，-1已删除)
     */
    public Byte getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>space.status</code>. 删除状态(0未删除，-1已删除)
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * Getter for <code>space.ctime</code>. 创建时间
     */
    public LocalDateTime getCtime() {
        return this.ctime;
    }

    /**
     * Setter for <code>space.ctime</code>. 创建时间
     */
    public void setCtime(LocalDateTime ctime) {
        this.ctime = ctime;
    }

    /**
     * Getter for <code>space.mtime</code>. 最后一次更新时间
     */
    public LocalDateTime getMtime() {
        return this.mtime;
    }

    /**
     * Setter for <code>space.mtime</code>. 最后一次更新时间
     */
    public void setMtime(LocalDateTime mtime) {
        this.mtime = mtime;
    }

    /**
     * Getter for <code>space.owner_uid</code>. 空间拥有人系统号
     */
    public String getOwnerUid() {
        return this.ownerUid;
    }

    /**
     * Setter for <code>space.owner_uid</code>. 空间拥有人系统号
     */
    public void setOwnerUid(String ownerUid) {
        this.ownerUid = ownerUid;
    }

    /**
     * Getter for <code>space.cuid</code>. 空间创建人系统号
     */
    public Long getCuid() {
        return this.cuid;
    }

    /**
     * Setter for <code>space.cuid</code>. 空间创建人系统号
     */
    public void setCuid(Long cuid) {
        this.cuid = cuid;
    }

    /**
     * Getter for <code>space.muid</code>. 空间最后一次更新人系统号
     */
    public Long getMuid() {
        return this.muid;
    }

    /**
     * Setter for <code>space.muid</code>. 空间最后一次更新人系统号
     */
    public void setMuid(Long muid) {
        this.muid = muid;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SpaceDB (");

        sb.append(id);
        sb.append(", ").append(spaceCode);
        sb.append(", ").append(spaceName);
        sb.append(", ").append(spaceDescription);
        sb.append(", ").append(status);
        sb.append(", ").append(ctime);
        sb.append(", ").append(mtime);
        sb.append(", ").append(ownerUid);
        sb.append(", ").append(cuid);
        sb.append(", ").append(muid);

        sb.append(")");
        return sb.toString();
    }
}
