/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.openapi.tables.pojos;


import com.ke.bella.openapi.db.repo.Operator;

import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * 团队表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TeamDB implements Operator, Serializable {

    private static final long serialVersionUID = 1L;

    private Long          id;
    private String        teamCode;
    private String        teamName;
    private String        teamDescription;
    private Byte          status;
    private LocalDateTime ctime;
    private LocalDateTime mtime;
    private Long          ownerUid;
    private String        ownerName;
    private String        cuName;
    private String        muName;
    private Long          cuid;
    private Long          muid;

    public TeamDB() {}

    public TeamDB(TeamDB value) {
        this.id = value.id;
        this.teamCode = value.teamCode;
        this.teamName = value.teamName;
        this.teamDescription = value.teamDescription;
        this.status = value.status;
        this.ctime = value.ctime;
        this.mtime = value.mtime;
        this.ownerUid = value.ownerUid;
        this.ownerName = value.ownerName;
        this.cuName = value.cuName;
        this.muName = value.muName;
        this.cuid = value.cuid;
        this.muid = value.muid;
    }

    public TeamDB(
        Long          id,
        String        teamCode,
        String        teamName,
        String        teamDescription,
        Byte          status,
        LocalDateTime ctime,
        LocalDateTime mtime,
        Long          ownerUid,
        String        ownerName,
        String        cuName,
        String        muName,
        Long          cuid,
        Long          muid
    ) {
        this.id = id;
        this.teamCode = teamCode;
        this.teamName = teamName;
        this.teamDescription = teamDescription;
        this.status = status;
        this.ctime = ctime;
        this.mtime = mtime;
        this.ownerUid = ownerUid;
        this.ownerName = ownerName;
        this.cuName = cuName;
        this.muName = muName;
        this.cuid = cuid;
        this.muid = muid;
    }

    /**
     * Getter for <code>team.id</code>. 主键
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>team.id</code>. 主键
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>team.team_code</code>. 团队编码
     */
    public String getTeamCode() {
        return this.teamCode;
    }

    /**
     * Setter for <code>team.team_code</code>. 团队编码
     */
    public void setTeamCode(String teamCode) {
        this.teamCode = teamCode;
    }

    /**
     * Getter for <code>team.team_name</code>. 团队名称
     */
    public String getTeamName() {
        return this.teamName;
    }

    /**
     * Setter for <code>team.team_name</code>. 团队名称
     */
    public void setTeamName(String teamName) {
        this.teamName = teamName;
    }

    /**
     * Getter for <code>team.team_description</code>. 团队描述
     */
    public String getTeamDescription() {
        return this.teamDescription;
    }

    /**
     * Setter for <code>team.team_description</code>. 团队描述
     */
    public void setTeamDescription(String teamDescription) {
        this.teamDescription = teamDescription;
    }

    /**
     * Getter for <code>team.status</code>. 删除状态(0未删除，-1已删除)
     */
    public Byte getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>team.status</code>. 删除状态(0未删除，-1已删除)
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * Getter for <code>team.ctime</code>. 创建时间
     */
    public LocalDateTime getCtime() {
        return this.ctime;
    }

    /**
     * Setter for <code>team.ctime</code>. 创建时间
     */
    public void setCtime(LocalDateTime ctime) {
        this.ctime = ctime;
    }

    /**
     * Getter for <code>team.mtime</code>. 最后一次更新时间
     */
    public LocalDateTime getMtime() {
        return this.mtime;
    }

    /**
     * Setter for <code>team.mtime</code>. 最后一次更新时间
     */
    public void setMtime(LocalDateTime mtime) {
        this.mtime = mtime;
    }

    /**
     * Getter for <code>team.owner_uid</code>. 团队拥有人系统号
     */
    public Long getOwnerUid() {
        return this.ownerUid;
    }

    /**
     * Setter for <code>team.owner_uid</code>. 团队拥有人系统号
     */
    public void setOwnerUid(Long ownerUid) {
        this.ownerUid = ownerUid;
    }

    /**
     * Getter for <code>team.owner_name</code>. 团队拥有人姓名
     */
    public String getOwnerName() {
        return this.ownerName;
    }

    /**
     * Setter for <code>team.owner_name</code>. 团队拥有人姓名
     */
    public void setOwnerName(String ownerName) {
        this.ownerName = ownerName;
    }

    /**
     * Getter for <code>team.cu_name</code>. 团队创建人姓名
     */
    public String getCuName() {
        return this.cuName;
    }

    /**
     * Setter for <code>team.cu_name</code>. 团队创建人姓名
     */
    public void setCuName(String cuName) {
        this.cuName = cuName;
    }

    /**
     * Getter for <code>team.mu_name</code>. 团队最后一次更新人姓名
     */
    public String getMuName() {
        return this.muName;
    }

    /**
     * Setter for <code>team.mu_name</code>. 团队最后一次更新人姓名
     */
    public void setMuName(String muName) {
        this.muName = muName;
    }

    /**
     * Getter for <code>team.cuid</code>. 团队创建人系统号
     */
    public Long getCuid() {
        return this.cuid;
    }

    /**
     * Setter for <code>team.cuid</code>. 团队创建人系统号
     */
    public void setCuid(Long cuid) {
        this.cuid = cuid;
    }

    /**
     * Getter for <code>team.muid</code>. 团队最后一次更新人系统号
     */
    public Long getMuid() {
        return this.muid;
    }

    /**
     * Setter for <code>team.muid</code>. 团队最后一次更新人系统号
     */
    public void setMuid(Long muid) {
        this.muid = muid;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TeamDB (");

        sb.append(id);
        sb.append(", ").append(teamCode);
        sb.append(", ").append(teamName);
        sb.append(", ").append(teamDescription);
        sb.append(", ").append(status);
        sb.append(", ").append(ctime);
        sb.append(", ").append(mtime);
        sb.append(", ").append(ownerUid);
        sb.append(", ").append(ownerName);
        sb.append(", ").append(cuName);
        sb.append(", ").append(muName);
        sb.append(", ").append(cuid);
        sb.append(", ").append(muid);

        sb.append(")");
        return sb.toString();
    }
}
