/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.openapi.tables.records;


import com.ke.bella.openapi.db.repo.Operator;
import com.ke.bella.openapi.tables.Model;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record16;
import org.jooq.Row16;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 模型
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ModelRecord extends UpdatableRecordImpl<ModelRecord> implements Operator, Record16<Long, String, String, String, String, String, String, String, String, String, Long, String, Long, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>model.id</code>. 主键ID
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>model.id</code>. 主键ID
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>model.model_name</code>. 模型名称
     */
    public void setModelName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>model.model_name</code>. 模型名称
     */
    public String getModelName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>model.document_url</code>. 文档地址
     */
    public void setDocumentUrl(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>model.document_url</code>. 文档地址
     */
    public String getDocumentUrl() {
        return (String) get(2);
    }

    /**
     * Setter for <code>model.visibility</code>. 是否公开(private/public)
     */
    public void setVisibility(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>model.visibility</code>. 是否公开(private/public)
     */
    public String getVisibility() {
        return (String) get(3);
    }

    /**
     * Setter for <code>model.owner_type</code>. 所有者类型（系统/组织/个人）
     */
    public void setOwnerType(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>model.owner_type</code>. 所有者类型（系统/组织/个人）
     */
    public String getOwnerType() {
        return (String) get(4);
    }

    /**
     * Setter for <code>model.owner_code</code>. 所有者系统号
     */
    public void setOwnerCode(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>model.owner_code</code>. 所有者系统号
     */
    public String getOwnerCode() {
        return (String) get(5);
    }

    /**
     * Setter for <code>model.owner_name</code>. 所有者名称
     */
    public void setOwnerName(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>model.owner_name</code>. 所有者名称
     */
    public String getOwnerName() {
        return (String) get(6);
    }

    /**
     * Setter for <code>model.status</code>. 状态(active/inactive)
     */
    public void setStatus(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>model.status</code>. 状态(active/inactive)
     */
    public String getStatus() {
        return (String) get(7);
    }

    /**
     * Setter for <code>model.properties</code>. 属性
     */
    public void setProperties(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>model.properties</code>. 属性
     */
    public String getProperties() {
        return (String) get(8);
    }

    /**
     * Setter for <code>model.features</code>. 特性
     */
    public void setFeatures(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>model.features</code>. 特性
     */
    public String getFeatures() {
        return (String) get(9);
    }

    /**
     * Setter for <code>model.cuid</code>. 创建人id
     */
    public void setCuid(Long value) {
        set(10, value);
    }

    /**
     * Getter for <code>model.cuid</code>. 创建人id
     */
    public Long getCuid() {
        return (Long) get(10);
    }

    /**
     * Setter for <code>model.cu_name</code>. 创建人姓名
     */
    public void setCuName(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>model.cu_name</code>. 创建人姓名
     */
    public String getCuName() {
        return (String) get(11);
    }

    /**
     * Setter for <code>model.muid</code>. 编辑人id
     */
    public void setMuid(Long value) {
        set(12, value);
    }

    /**
     * Getter for <code>model.muid</code>. 编辑人id
     */
    public Long getMuid() {
        return (Long) get(12);
    }

    /**
     * Setter for <code>model.mu_name</code>. 编辑人姓名
     */
    public void setMuName(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>model.mu_name</code>. 编辑人姓名
     */
    public String getMuName() {
        return (String) get(13);
    }

    /**
     * Setter for <code>model.ctime</code>.
     */
    public void setCtime(LocalDateTime value) {
        set(14, value);
    }

    /**
     * Getter for <code>model.ctime</code>.
     */
    public LocalDateTime getCtime() {
        return (LocalDateTime) get(14);
    }

    /**
     * Setter for <code>model.mtime</code>.
     */
    public void setMtime(LocalDateTime value) {
        set(15, value);
    }

    /**
     * Getter for <code>model.mtime</code>.
     */
    public LocalDateTime getMtime() {
        return (LocalDateTime) get(15);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record16 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row16<Long, String, String, String, String, String, String, String, String, String, Long, String, Long, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row16) super.fieldsRow();
    }

    @Override
    public Row16<Long, String, String, String, String, String, String, String, String, String, Long, String, Long, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row16) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Model.MODEL.ID;
    }

    @Override
    public Field<String> field2() {
        return Model.MODEL.MODEL_NAME;
    }

    @Override
    public Field<String> field3() {
        return Model.MODEL.DOCUMENT_URL;
    }

    @Override
    public Field<String> field4() {
        return Model.MODEL.VISIBILITY;
    }

    @Override
    public Field<String> field5() {
        return Model.MODEL.OWNER_TYPE;
    }

    @Override
    public Field<String> field6() {
        return Model.MODEL.OWNER_CODE;
    }

    @Override
    public Field<String> field7() {
        return Model.MODEL.OWNER_NAME;
    }

    @Override
    public Field<String> field8() {
        return Model.MODEL.STATUS;
    }

    @Override
    public Field<String> field9() {
        return Model.MODEL.PROPERTIES;
    }

    @Override
    public Field<String> field10() {
        return Model.MODEL.FEATURES;
    }

    @Override
    public Field<Long> field11() {
        return Model.MODEL.CUID;
    }

    @Override
    public Field<String> field12() {
        return Model.MODEL.CU_NAME;
    }

    @Override
    public Field<Long> field13() {
        return Model.MODEL.MUID;
    }

    @Override
    public Field<String> field14() {
        return Model.MODEL.MU_NAME;
    }

    @Override
    public Field<LocalDateTime> field15() {
        return Model.MODEL.CTIME;
    }

    @Override
    public Field<LocalDateTime> field16() {
        return Model.MODEL.MTIME;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getModelName();
    }

    @Override
    public String component3() {
        return getDocumentUrl();
    }

    @Override
    public String component4() {
        return getVisibility();
    }

    @Override
    public String component5() {
        return getOwnerType();
    }

    @Override
    public String component6() {
        return getOwnerCode();
    }

    @Override
    public String component7() {
        return getOwnerName();
    }

    @Override
    public String component8() {
        return getStatus();
    }

    @Override
    public String component9() {
        return getProperties();
    }

    @Override
    public String component10() {
        return getFeatures();
    }

    @Override
    public Long component11() {
        return getCuid();
    }

    @Override
    public String component12() {
        return getCuName();
    }

    @Override
    public Long component13() {
        return getMuid();
    }

    @Override
    public String component14() {
        return getMuName();
    }

    @Override
    public LocalDateTime component15() {
        return getCtime();
    }

    @Override
    public LocalDateTime component16() {
        return getMtime();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getModelName();
    }

    @Override
    public String value3() {
        return getDocumentUrl();
    }

    @Override
    public String value4() {
        return getVisibility();
    }

    @Override
    public String value5() {
        return getOwnerType();
    }

    @Override
    public String value6() {
        return getOwnerCode();
    }

    @Override
    public String value7() {
        return getOwnerName();
    }

    @Override
    public String value8() {
        return getStatus();
    }

    @Override
    public String value9() {
        return getProperties();
    }

    @Override
    public String value10() {
        return getFeatures();
    }

    @Override
    public Long value11() {
        return getCuid();
    }

    @Override
    public String value12() {
        return getCuName();
    }

    @Override
    public Long value13() {
        return getMuid();
    }

    @Override
    public String value14() {
        return getMuName();
    }

    @Override
    public LocalDateTime value15() {
        return getCtime();
    }

    @Override
    public LocalDateTime value16() {
        return getMtime();
    }

    @Override
    public ModelRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public ModelRecord value2(String value) {
        setModelName(value);
        return this;
    }

    @Override
    public ModelRecord value3(String value) {
        setDocumentUrl(value);
        return this;
    }

    @Override
    public ModelRecord value4(String value) {
        setVisibility(value);
        return this;
    }

    @Override
    public ModelRecord value5(String value) {
        setOwnerType(value);
        return this;
    }

    @Override
    public ModelRecord value6(String value) {
        setOwnerCode(value);
        return this;
    }

    @Override
    public ModelRecord value7(String value) {
        setOwnerName(value);
        return this;
    }

    @Override
    public ModelRecord value8(String value) {
        setStatus(value);
        return this;
    }

    @Override
    public ModelRecord value9(String value) {
        setProperties(value);
        return this;
    }

    @Override
    public ModelRecord value10(String value) {
        setFeatures(value);
        return this;
    }

    @Override
    public ModelRecord value11(Long value) {
        setCuid(value);
        return this;
    }

    @Override
    public ModelRecord value12(String value) {
        setCuName(value);
        return this;
    }

    @Override
    public ModelRecord value13(Long value) {
        setMuid(value);
        return this;
    }

    @Override
    public ModelRecord value14(String value) {
        setMuName(value);
        return this;
    }

    @Override
    public ModelRecord value15(LocalDateTime value) {
        setCtime(value);
        return this;
    }

    @Override
    public ModelRecord value16(LocalDateTime value) {
        setMtime(value);
        return this;
    }

    @Override
    public ModelRecord values(Long value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10, Long value11, String value12, Long value13, String value14, LocalDateTime value15, LocalDateTime value16) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ModelRecord
     */
    public ModelRecord() {
        super(Model.MODEL);
    }

    /**
     * Create a detached, initialised ModelRecord
     */
    public ModelRecord(Long id, String modelName, String documentUrl, String visibility, String ownerType, String ownerCode, String ownerName, String status, String properties, String features, Long cuid, String cuName, Long muid, String muName, LocalDateTime ctime, LocalDateTime mtime) {
        super(Model.MODEL);

        setId(id);
        setModelName(modelName);
        setDocumentUrl(documentUrl);
        setVisibility(visibility);
        setOwnerType(ownerType);
        setOwnerCode(ownerCode);
        setOwnerName(ownerName);
        setStatus(status);
        setProperties(properties);
        setFeatures(features);
        setCuid(cuid);
        setCuName(cuName);
        setMuid(muid);
        setMuName(muName);
        setCtime(ctime);
        setMtime(mtime);
    }
}
