/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.openapi.tables.records;


import com.ke.bella.openapi.db.repo.Operator;
import com.ke.bella.openapi.tables.TeamMember;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 团队成员信息表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TeamMemberRecord extends UpdatableRecordImpl<TeamMemberRecord> implements Operator, Record12<Long, String, String, Long, String, Byte, LocalDateTime, LocalDateTime, Long, Long, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>team_member.id</code>. 主键
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>team_member.id</code>. 主键
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>team_member.team_code</code>. 团队编码
     */
    public void setTeamCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>team_member.team_code</code>. 团队编码
     */
    public String getTeamCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>team_member.role_code</code>. 角色编码
     */
    public void setRoleCode(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>team_member.role_code</code>. 角色编码
     */
    public String getRoleCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>team_member.member_uid</code>. 成员系统号
     */
    public void setMemberUid(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>team_member.member_uid</code>. 成员系统号
     */
    public Long getMemberUid() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>team_member.member_name</code>. 成员用户名
     */
    public void setMemberName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>team_member.member_name</code>. 成员用户名
     */
    public String getMemberName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>team_member.status</code>. 删除状态(0未删除，-1已删除)
     */
    public void setStatus(Byte value) {
        set(5, value);
    }

    /**
     * Getter for <code>team_member.status</code>. 删除状态(0未删除，-1已删除)
     */
    public Byte getStatus() {
        return (Byte) get(5);
    }

    /**
     * Setter for <code>team_member.ctime</code>. 创建时间
     */
    public void setCtime(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>team_member.ctime</code>. 创建时间
     */
    public LocalDateTime getCtime() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>team_member.mtime</code>. 最后一次修改时间
     */
    public void setMtime(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>team_member.mtime</code>. 最后一次修改时间
     */
    public LocalDateTime getMtime() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>team_member.cuid</code>. 创建人系统号
     */
    public void setCuid(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>team_member.cuid</code>. 创建人系统号
     */
    public Long getCuid() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>team_member.muid</code>. 最后一次更新人系统号
     */
    public void setMuid(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>team_member.muid</code>. 最后一次更新人系统号
     */
    public Long getMuid() {
        return (Long) get(9);
    }

    /**
     * Setter for <code>team_member.cu_name</code>. 团队创建人姓名
     */
    public void setCuName(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>team_member.cu_name</code>. 团队创建人姓名
     */
    public String getCuName() {
        return (String) get(10);
    }

    /**
     * Setter for <code>team_member.mu_name</code>. 团队最后一次更新人姓名
     */
    public void setMuName(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>team_member.mu_name</code>. 团队最后一次更新人姓名
     */
    public String getMuName() {
        return (String) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row12<Long, String, String, Long, String, Byte, LocalDateTime, LocalDateTime, Long, Long, String, String> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    @Override
    public Row12<Long, String, String, Long, String, Byte, LocalDateTime, LocalDateTime, Long, Long, String, String> valuesRow() {
        return (Row12) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return TeamMember.TEAM_MEMBER.ID;
    }

    @Override
    public Field<String> field2() {
        return TeamMember.TEAM_MEMBER.TEAM_CODE;
    }

    @Override
    public Field<String> field3() {
        return TeamMember.TEAM_MEMBER.ROLE_CODE;
    }

    @Override
    public Field<Long> field4() {
        return TeamMember.TEAM_MEMBER.MEMBER_UID;
    }

    @Override
    public Field<String> field5() {
        return TeamMember.TEAM_MEMBER.MEMBER_NAME;
    }

    @Override
    public Field<Byte> field6() {
        return TeamMember.TEAM_MEMBER.STATUS;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return TeamMember.TEAM_MEMBER.CTIME;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return TeamMember.TEAM_MEMBER.MTIME;
    }

    @Override
    public Field<Long> field9() {
        return TeamMember.TEAM_MEMBER.CUID;
    }

    @Override
    public Field<Long> field10() {
        return TeamMember.TEAM_MEMBER.MUID;
    }

    @Override
    public Field<String> field11() {
        return TeamMember.TEAM_MEMBER.CU_NAME;
    }

    @Override
    public Field<String> field12() {
        return TeamMember.TEAM_MEMBER.MU_NAME;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getTeamCode();
    }

    @Override
    public String component3() {
        return getRoleCode();
    }

    @Override
    public Long component4() {
        return getMemberUid();
    }

    @Override
    public String component5() {
        return getMemberName();
    }

    @Override
    public Byte component6() {
        return getStatus();
    }

    @Override
    public LocalDateTime component7() {
        return getCtime();
    }

    @Override
    public LocalDateTime component8() {
        return getMtime();
    }

    @Override
    public Long component9() {
        return getCuid();
    }

    @Override
    public Long component10() {
        return getMuid();
    }

    @Override
    public String component11() {
        return getCuName();
    }

    @Override
    public String component12() {
        return getMuName();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getTeamCode();
    }

    @Override
    public String value3() {
        return getRoleCode();
    }

    @Override
    public Long value4() {
        return getMemberUid();
    }

    @Override
    public String value5() {
        return getMemberName();
    }

    @Override
    public Byte value6() {
        return getStatus();
    }

    @Override
    public LocalDateTime value7() {
        return getCtime();
    }

    @Override
    public LocalDateTime value8() {
        return getMtime();
    }

    @Override
    public Long value9() {
        return getCuid();
    }

    @Override
    public Long value10() {
        return getMuid();
    }

    @Override
    public String value11() {
        return getCuName();
    }

    @Override
    public String value12() {
        return getMuName();
    }

    @Override
    public TeamMemberRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public TeamMemberRecord value2(String value) {
        setTeamCode(value);
        return this;
    }

    @Override
    public TeamMemberRecord value3(String value) {
        setRoleCode(value);
        return this;
    }

    @Override
    public TeamMemberRecord value4(Long value) {
        setMemberUid(value);
        return this;
    }

    @Override
    public TeamMemberRecord value5(String value) {
        setMemberName(value);
        return this;
    }

    @Override
    public TeamMemberRecord value6(Byte value) {
        setStatus(value);
        return this;
    }

    @Override
    public TeamMemberRecord value7(LocalDateTime value) {
        setCtime(value);
        return this;
    }

    @Override
    public TeamMemberRecord value8(LocalDateTime value) {
        setMtime(value);
        return this;
    }

    @Override
    public TeamMemberRecord value9(Long value) {
        setCuid(value);
        return this;
    }

    @Override
    public TeamMemberRecord value10(Long value) {
        setMuid(value);
        return this;
    }

    @Override
    public TeamMemberRecord value11(String value) {
        setCuName(value);
        return this;
    }

    @Override
    public TeamMemberRecord value12(String value) {
        setMuName(value);
        return this;
    }

    @Override
    public TeamMemberRecord values(Long value1, String value2, String value3, Long value4, String value5, Byte value6, LocalDateTime value7, LocalDateTime value8, Long value9, Long value10, String value11, String value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TeamMemberRecord
     */
    public TeamMemberRecord() {
        super(TeamMember.TEAM_MEMBER);
    }

    /**
     * Create a detached, initialised TeamMemberRecord
     */
    public TeamMemberRecord(Long id, String teamCode, String roleCode, Long memberUid, String memberName, Byte status, LocalDateTime ctime, LocalDateTime mtime, Long cuid, Long muid, String cuName, String muName) {
        super(TeamMember.TEAM_MEMBER);

        setId(id);
        setTeamCode(teamCode);
        setRoleCode(roleCode);
        setMemberUid(memberUid);
        setMemberName(memberName);
        setStatus(status);
        setCtime(ctime);
        setMtime(mtime);
        setCuid(cuid);
        setMuid(muid);
        setCuName(cuName);
        setMuName(muName);
    }
}
