/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.openapi.tables;


import com.ke.bella.openapi.DefaultSchema;
import com.ke.bella.openapi.Keys;
import com.ke.bella.openapi.tables.records.ApikeyRoleRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row9;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * ak角色
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ApikeyRole extends TableImpl<ApikeyRoleRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>apikey_role</code>
     */
    public static final ApikeyRole APIKEY_ROLE = new ApikeyRole();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ApikeyRoleRecord> getRecordType() {
        return ApikeyRoleRecord.class;
    }

    /**
     * The column <code>apikey_role.id</code>. 主键ID
     */
    public final TableField<ApikeyRoleRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "主键ID");

    /**
     * The column <code>apikey_role.role_code</code>. ak编码
     */
    public final TableField<ApikeyRoleRecord, String> ROLE_CODE = createField(DSL.name("role_code"), SQLDataType.VARCHAR(64).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "ak编码");

    /**
     * The column <code>apikey_role.path</code>. 授权的path
     */
    public final TableField<ApikeyRoleRecord, String> PATH = createField(DSL.name("path"), SQLDataType.CLOB.nullable(false), this, "授权的path");

    /**
     * The column <code>apikey_role.cuid</code>. 创建人id
     */
    public final TableField<ApikeyRoleRecord, Long> CUID = createField(DSL.name("cuid"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.BIGINT)), this, "创建人id");

    /**
     * The column <code>apikey_role.cu_name</code>. 创建人姓名
     */
    public final TableField<ApikeyRoleRecord, String> CU_NAME = createField(DSL.name("cu_name"), SQLDataType.VARCHAR(16).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "创建人姓名");

    /**
     * The column <code>apikey_role.muid</code>. 编辑人id
     */
    public final TableField<ApikeyRoleRecord, Long> MUID = createField(DSL.name("muid"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.BIGINT)), this, "编辑人id");

    /**
     * The column <code>apikey_role.mu_name</code>. 编辑人姓名
     */
    public final TableField<ApikeyRoleRecord, String> MU_NAME = createField(DSL.name("mu_name"), SQLDataType.VARCHAR(16).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "编辑人姓名");

    /**
     * The column <code>apikey_role.ctime</code>.
     */
    public final TableField<ApikeyRoleRecord, LocalDateTime> CTIME = createField(DSL.name("ctime"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>apikey_role.mtime</code>.
     */
    public final TableField<ApikeyRoleRecord, LocalDateTime> MTIME = createField(DSL.name("mtime"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "");

    private ApikeyRole(Name alias, Table<ApikeyRoleRecord> aliased) {
        this(alias, aliased, null);
    }

    private ApikeyRole(Name alias, Table<ApikeyRoleRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("ak角色"), TableOptions.table());
    }

    /**
     * Create an aliased <code>apikey_role</code> table reference
     */
    public ApikeyRole(String alias) {
        this(DSL.name(alias), APIKEY_ROLE);
    }

    /**
     * Create an aliased <code>apikey_role</code> table reference
     */
    public ApikeyRole(Name alias) {
        this(alias, APIKEY_ROLE);
    }

    /**
     * Create a <code>apikey_role</code> table reference
     */
    public ApikeyRole() {
        this(DSL.name("apikey_role"), null);
    }

    public <O extends Record> ApikeyRole(Table<O> child, ForeignKey<O, ApikeyRoleRecord> key) {
        super(child, key, APIKEY_ROLE);
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public Identity<ApikeyRoleRecord, Long> getIdentity() {
        return (Identity<ApikeyRoleRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<ApikeyRoleRecord> getPrimaryKey() {
        return Keys.KEY_APIKEY_ROLE_PRIMARY;
    }

    @Override
    public List<UniqueKey<ApikeyRoleRecord>> getKeys() {
        return Arrays.<UniqueKey<ApikeyRoleRecord>>asList(Keys.KEY_APIKEY_ROLE_PRIMARY, Keys.KEY_APIKEY_ROLE_UNIQ_IDX_ROLE_CODE);
    }

    @Override
    public ApikeyRole as(String alias) {
        return new ApikeyRole(DSL.name(alias), this);
    }

    @Override
    public ApikeyRole as(Name alias) {
        return new ApikeyRole(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ApikeyRole rename(String name) {
        return new ApikeyRole(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ApikeyRole rename(Name name) {
        return new ApikeyRole(name, null);
    }

    // -------------------------------------------------------------------------
    // Row9 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row9<Long, String, String, Long, String, Long, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row9) super.fieldsRow();
    }
}
