/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.openapi.tables;


import com.ke.bella.openapi.DefaultSchema;
import com.ke.bella.openapi.Indexes;
import com.ke.bella.openapi.Keys;
import com.ke.bella.openapi.tables.records.ApiKeyMonthCostRecord;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row6;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * ak月花费
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ApiKeyMonthCost extends TableImpl<ApiKeyMonthCostRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>api_key_month_cost</code>
     */
    public static final ApiKeyMonthCost API_KEY_MONTH_COST = new ApiKeyMonthCost();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ApiKeyMonthCostRecord> getRecordType() {
        return ApiKeyMonthCostRecord.class;
    }

    /**
     * The column <code>api_key_month_cost.id</code>. 主键ID
     */
    public final TableField<ApiKeyMonthCostRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "主键ID");

    /**
     * The column <code>api_key_month_cost.ak_code</code>. ak编码
     */
    public final TableField<ApiKeyMonthCostRecord, String> AK_CODE = createField(DSL.name("ak_code"), SQLDataType.VARCHAR(64).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "ak编码");

    /**
     * The column <code>api_key_month_cost.month</code>. 月份
     */
    public final TableField<ApiKeyMonthCostRecord, String> MONTH = createField(DSL.name("month"), SQLDataType.VARCHAR(16).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "月份");

    /**
     * The column <code>api_key_month_cost.amount</code>. 开销（分）
     */
    public final TableField<ApiKeyMonthCostRecord, BigDecimal> AMOUNT = createField(DSL.name("amount"), SQLDataType.DECIMAL(12, 4).nullable(false).defaultValue(DSL.inline("0.0000", SQLDataType.DECIMAL)), this, "开销（分）");

    /**
     * The column <code>api_key_month_cost.ctime</code>.
     */
    public final TableField<ApiKeyMonthCostRecord, LocalDateTime> CTIME = createField(DSL.name("ctime"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>api_key_month_cost.mtime</code>.
     */
    public final TableField<ApiKeyMonthCostRecord, LocalDateTime> MTIME = createField(DSL.name("mtime"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "");

    private ApiKeyMonthCost(Name alias, Table<ApiKeyMonthCostRecord> aliased) {
        this(alias, aliased, null);
    }

    private ApiKeyMonthCost(Name alias, Table<ApiKeyMonthCostRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("ak月花费"), TableOptions.table());
    }

    /**
     * Create an aliased <code>api_key_month_cost</code> table reference
     */
    public ApiKeyMonthCost(String alias) {
        this(DSL.name(alias), API_KEY_MONTH_COST);
    }

    /**
     * Create an aliased <code>api_key_month_cost</code> table reference
     */
    public ApiKeyMonthCost(Name alias) {
        this(alias, API_KEY_MONTH_COST);
    }

    /**
     * Create a <code>api_key_month_cost</code> table reference
     */
    public ApiKeyMonthCost() {
        this(DSL.name("api_key_month_cost"), null);
    }

    public <O extends Record> ApiKeyMonthCost(Table<O> child, ForeignKey<O, ApiKeyMonthCostRecord> key) {
        super(child, key, API_KEY_MONTH_COST);
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.API_KEY_MONTH_COST_IDX_MONTH);
    }

    @Override
    public Identity<ApiKeyMonthCostRecord, Long> getIdentity() {
        return (Identity<ApiKeyMonthCostRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<ApiKeyMonthCostRecord> getPrimaryKey() {
        return Keys.KEY_API_KEY_MONTH_COST_PRIMARY;
    }

    @Override
    public List<UniqueKey<ApiKeyMonthCostRecord>> getKeys() {
        return Arrays.<UniqueKey<ApiKeyMonthCostRecord>>asList(Keys.KEY_API_KEY_MONTH_COST_PRIMARY, Keys.KEY_API_KEY_MONTH_COST_UNIQ_IDX_AK_CODE_MONTH);
    }

    @Override
    public ApiKeyMonthCost as(String alias) {
        return new ApiKeyMonthCost(DSL.name(alias), this);
    }

    @Override
    public ApiKeyMonthCost as(Name alias) {
        return new ApiKeyMonthCost(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ApiKeyMonthCost rename(String name) {
        return new ApiKeyMonthCost(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ApiKeyMonthCost rename(Name name) {
        return new ApiKeyMonthCost(name, null);
    }

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, String, String, BigDecimal, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }
}
