/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.openapi.tables;


import com.ke.bella.openapi.DefaultSchema;
import com.ke.bella.openapi.Indexes;
import com.ke.bella.openapi.Keys;
import com.ke.bella.openapi.tables.records.EndpointRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * openapi能力点
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Endpoint extends TableImpl<EndpointRecord> {

    private static final long serialVersionUID = 1385572231;

    /**
     * The reference instance of <code>endpoint</code>
     */
    public static final Endpoint ENDPOINT = new Endpoint();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<EndpointRecord> getRecordType() {
        return EndpointRecord.class;
    }

    /**
     * The column <code>endpoint.id</code>. 主键ID
     */
    public final TableField<EndpointRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "主键ID");

    /**
     * The column <code>endpoint.endpoint</code>. 请求path
     */
    public final TableField<EndpointRecord, String> ENDPOINT_ = createField("endpoint", org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "请求path");

    /**
     * The column <code>endpoint.endpoint_code</code>. 能力点编码
     */
    public final TableField<EndpointRecord, String> ENDPOINT_CODE = createField("endpoint_code", org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "能力点编码");

    /**
     * The column <code>endpoint.endpoint_name</code>. 能力点名称
     */
    public final TableField<EndpointRecord, String> ENDPOINT_NAME = createField("endpoint_name", org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "能力点名称");

    /**
     * The column <code>endpoint.maintainer_code</code>. 维护人系统号
     */
    public final TableField<EndpointRecord, String> MAINTAINER_CODE = createField("maintainer_code", org.jooq.impl.SQLDataType.VARCHAR(16).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "维护人系统号");

    /**
     * The column <code>endpoint.maintainer_name</code>. 维护人姓名
     */
    public final TableField<EndpointRecord, String> MAINTAINER_NAME = createField("maintainer_name", org.jooq.impl.SQLDataType.VARCHAR(16).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "维护人姓名");

    /**
     * The column <code>endpoint.status</code>. 状态(active/inactive)
     */
    public final TableField<EndpointRecord, String> STATUS = createField("status", org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false).defaultValue(org.jooq.impl.DSL.inline("active", org.jooq.impl.SQLDataType.VARCHAR)), this, "状态(active/inactive)");

    /**
     * The column <code>endpoint.cuid</code>. 创建人id
     */
    public final TableField<EndpointRecord, Long> CUID = createField("cuid", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.BIGINT)), this, "创建人id");

    /**
     * The column <code>endpoint.cu_name</code>. 创建人姓名
     */
    public final TableField<EndpointRecord, String> CU_NAME = createField("cu_name", org.jooq.impl.SQLDataType.VARCHAR(16).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "创建人姓名");

    /**
     * The column <code>endpoint.muid</code>. 编辑人id
     */
    public final TableField<EndpointRecord, Long> MUID = createField("muid", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.BIGINT)), this, "编辑人id");

    /**
     * The column <code>endpoint.mu_name</code>. 编辑人姓名
     */
    public final TableField<EndpointRecord, String> MU_NAME = createField("mu_name", org.jooq.impl.SQLDataType.VARCHAR(16).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "编辑人姓名");

    /**
     * The column <code>endpoint.ctime</code>.
     */
    public final TableField<EndpointRecord, Timestamp> CTIME = createField("ctime", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>endpoint.mtime</code>.
     */
    public final TableField<EndpointRecord, Timestamp> MTIME = createField("mtime", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>endpoint</code> table reference
     */
    public Endpoint() {
        this(DSL.name("endpoint"), null);
    }

    /**
     * Create an aliased <code>endpoint</code> table reference
     */
    public Endpoint(String alias) {
        this(DSL.name(alias), ENDPOINT);
    }

    /**
     * Create an aliased <code>endpoint</code> table reference
     */
    public Endpoint(Name alias) {
        this(alias, ENDPOINT);
    }

    private Endpoint(Name alias, Table<EndpointRecord> aliased) {
        this(alias, aliased, null);
    }

    private Endpoint(Name alias, Table<EndpointRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("openapi能力点"));
    }

    public <O extends Record> Endpoint(Table<O> child, ForeignKey<O, EndpointRecord> key) {
        super(child, key, ENDPOINT);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.ENDPOINT_PRIMARY, Indexes.ENDPOINT_UNIQ_IDX_UNI_ENDPOINT, Indexes.ENDPOINT_UNIQ_IDX_UNI_ENDPOINT_CODE, Indexes.ENDPOINT_UNIQ_IDX_UNI_ENDPOINT_NAME);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<EndpointRecord, Long> getIdentity() {
        return Keys.IDENTITY_ENDPOINT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<EndpointRecord> getPrimaryKey() {
        return Keys.KEY_ENDPOINT_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<EndpointRecord>> getKeys() {
        return Arrays.<UniqueKey<EndpointRecord>>asList(Keys.KEY_ENDPOINT_PRIMARY, Keys.KEY_ENDPOINT_UNIQ_IDX_UNI_ENDPOINT, Keys.KEY_ENDPOINT_UNIQ_IDX_UNI_ENDPOINT_CODE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Endpoint as(String alias) {
        return new Endpoint(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Endpoint as(Name alias) {
        return new Endpoint(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Endpoint rename(String name) {
        return new Endpoint(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Endpoint rename(Name name) {
        return new Endpoint(name, null);
    }
}
