/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.openapi.tables;


import com.ke.bella.openapi.DefaultSchema;
import com.ke.bella.openapi.Indexes;
import com.ke.bella.openapi.Keys;
import com.ke.bella.openapi.tables.records.ModelEndpointRelRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * openapi模型能力点
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ModelEndpointRel extends TableImpl<ModelEndpointRelRecord> {

    private static final long serialVersionUID = 1894488148;

    /**
     * The reference instance of <code>model_endpoint_rel</code>
     */
    public static final ModelEndpointRel MODEL_ENDPOINT_REL = new ModelEndpointRel();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ModelEndpointRelRecord> getRecordType() {
        return ModelEndpointRelRecord.class;
    }

    /**
     * The column <code>model_endpoint_rel.id</code>. 主键ID
     */
    public final TableField<ModelEndpointRelRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "主键ID");

    /**
     * The column <code>model_endpoint_rel.model_name</code>. 模型名称
     */
    public final TableField<ModelEndpointRelRecord, String> MODEL_NAME = createField("model_name", org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "模型名称");

    /**
     * The column <code>model_endpoint_rel.endpoint</code>. 请求path
     */
    public final TableField<ModelEndpointRelRecord, String> ENDPOINT = createField("endpoint", org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "请求path");

    /**
     * The column <code>model_endpoint_rel.cuid</code>. 创建人id
     */
    public final TableField<ModelEndpointRelRecord, Long> CUID = createField("cuid", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.BIGINT)), this, "创建人id");

    /**
     * The column <code>model_endpoint_rel.cu_name</code>. 创建人姓名
     */
    public final TableField<ModelEndpointRelRecord, String> CU_NAME = createField("cu_name", org.jooq.impl.SQLDataType.VARCHAR(16).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "创建人姓名");

    /**
     * The column <code>model_endpoint_rel.muid</code>. 编辑人id
     */
    public final TableField<ModelEndpointRelRecord, Long> MUID = createField("muid", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.BIGINT)), this, "编辑人id");

    /**
     * The column <code>model_endpoint_rel.mu_name</code>. 编辑人姓名
     */
    public final TableField<ModelEndpointRelRecord, String> MU_NAME = createField("mu_name", org.jooq.impl.SQLDataType.VARCHAR(16).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "编辑人姓名");

    /**
     * The column <code>model_endpoint_rel.ctime</code>.
     */
    public final TableField<ModelEndpointRelRecord, Timestamp> CTIME = createField("ctime", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>model_endpoint_rel.mtime</code>.
     */
    public final TableField<ModelEndpointRelRecord, Timestamp> MTIME = createField("mtime", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>model_endpoint_rel</code> table reference
     */
    public ModelEndpointRel() {
        this(DSL.name("model_endpoint_rel"), null);
    }

    /**
     * Create an aliased <code>model_endpoint_rel</code> table reference
     */
    public ModelEndpointRel(String alias) {
        this(DSL.name(alias), MODEL_ENDPOINT_REL);
    }

    /**
     * Create an aliased <code>model_endpoint_rel</code> table reference
     */
    public ModelEndpointRel(Name alias) {
        this(alias, MODEL_ENDPOINT_REL);
    }

    private ModelEndpointRel(Name alias, Table<ModelEndpointRelRecord> aliased) {
        this(alias, aliased, null);
    }

    private ModelEndpointRel(Name alias, Table<ModelEndpointRelRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("openapi模型能力点"));
    }

    public <O extends Record> ModelEndpointRel(Table<O> child, ForeignKey<O, ModelEndpointRelRecord> key) {
        super(child, key, MODEL_ENDPOINT_REL);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.MODEL_ENDPOINT_REL_IDX_MODEL_NAME, Indexes.MODEL_ENDPOINT_REL_PRIMARY, Indexes.MODEL_ENDPOINT_REL_UNIQ_IDX_UNI_ENDPOINT_MODEL);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ModelEndpointRelRecord, Long> getIdentity() {
        return Keys.IDENTITY_MODEL_ENDPOINT_REL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ModelEndpointRelRecord> getPrimaryKey() {
        return Keys.KEY_MODEL_ENDPOINT_REL_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ModelEndpointRelRecord>> getKeys() {
        return Arrays.<UniqueKey<ModelEndpointRelRecord>>asList(Keys.KEY_MODEL_ENDPOINT_REL_PRIMARY, Keys.KEY_MODEL_ENDPOINT_REL_UNIQ_IDX_UNI_ENDPOINT_MODEL);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ModelEndpointRel as(String alias) {
        return new ModelEndpointRel(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ModelEndpointRel as(Name alias) {
        return new ModelEndpointRel(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ModelEndpointRel rename(String name) {
        return new ModelEndpointRel(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ModelEndpointRel rename(Name name) {
        return new ModelEndpointRel(name, null);
    }
}
