/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.openapi.tables;


import com.ke.bella.openapi.DefaultSchema;
import com.ke.bella.openapi.Indexes;
import com.ke.bella.openapi.Keys;
import com.ke.bella.openapi.tables.records.OpenapiEndpointRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * openapi能力点
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OpenapiEndpoint extends TableImpl<OpenapiEndpointRecord> {

    private static final long serialVersionUID = -1768295618;

    /**
     * The reference instance of <code>openapi_endpoint</code>
     */
    public static final OpenapiEndpoint OPENAPI_ENDPOINT = new OpenapiEndpoint();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OpenapiEndpointRecord> getRecordType() {
        return OpenapiEndpointRecord.class;
    }

    /**
     * The column <code>openapi_endpoint.id</code>. 主键ID
     */
    public final TableField<OpenapiEndpointRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "主键ID");

    /**
     * The column <code>openapi_endpoint.endpoint</code>. 请求path
     */
    public final TableField<OpenapiEndpointRecord, String> ENDPOINT = createField("endpoint", org.jooq.impl.SQLDataType.VARCHAR(256).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "请求path");

    /**
     * The column <code>openapi_endpoint.endpoint_name</code>. 能力点名称
     */
    public final TableField<OpenapiEndpointRecord, String> ENDPOINT_NAME = createField("endpoint_name", org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "能力点名称");

    /**
     * The column <code>openapi_endpoint.maintainer_code</code>. 维护人系统号
     */
    public final TableField<OpenapiEndpointRecord, String> MAINTAINER_CODE = createField("maintainer_code", org.jooq.impl.SQLDataType.VARCHAR(16).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "维护人系统号");

    /**
     * The column <code>openapi_endpoint.maintainer_name</code>. 维护人姓名
     */
    public final TableField<OpenapiEndpointRecord, String> MAINTAINER_NAME = createField("maintainer_name", org.jooq.impl.SQLDataType.VARCHAR(16).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "维护人姓名");

    /**
     * The column <code>openapi_endpoint.status</code>. 状态(active/inactive)
     */
    public final TableField<OpenapiEndpointRecord, String> STATUS = createField("status", org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false).defaultValue(org.jooq.impl.DSL.inline("active", org.jooq.impl.SQLDataType.VARCHAR)), this, "状态(active/inactive)");

    /**
     * The column <code>openapi_endpoint.cuid</code>. 创建人id
     */
    public final TableField<OpenapiEndpointRecord, Long> CUID = createField("cuid", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.BIGINT)), this, "创建人id");

    /**
     * The column <code>openapi_endpoint.cu_name</code>. 创建人姓名
     */
    public final TableField<OpenapiEndpointRecord, String> CU_NAME = createField("cu_name", org.jooq.impl.SQLDataType.VARCHAR(16).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "创建人姓名");

    /**
     * The column <code>openapi_endpoint.muid</code>. 编辑人id
     */
    public final TableField<OpenapiEndpointRecord, Long> MUID = createField("muid", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.BIGINT)), this, "编辑人id");

    /**
     * The column <code>openapi_endpoint.mu_name</code>. 编辑人姓名
     */
    public final TableField<OpenapiEndpointRecord, String> MU_NAME = createField("mu_name", org.jooq.impl.SQLDataType.VARCHAR(16).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "编辑人姓名");

    /**
     * The column <code>openapi_endpoint.ctime</code>.
     */
    public final TableField<OpenapiEndpointRecord, Timestamp> CTIME = createField("ctime", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>openapi_endpoint.mtime</code>.
     */
    public final TableField<OpenapiEndpointRecord, Timestamp> MTIME = createField("mtime", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>openapi_endpoint</code> table reference
     */
    public OpenapiEndpoint() {
        this(DSL.name("openapi_endpoint"), null);
    }

    /**
     * Create an aliased <code>openapi_endpoint</code> table reference
     */
    public OpenapiEndpoint(String alias) {
        this(DSL.name(alias), OPENAPI_ENDPOINT);
    }

    /**
     * Create an aliased <code>openapi_endpoint</code> table reference
     */
    public OpenapiEndpoint(Name alias) {
        this(alias, OPENAPI_ENDPOINT);
    }

    private OpenapiEndpoint(Name alias, Table<OpenapiEndpointRecord> aliased) {
        this(alias, aliased, null);
    }

    private OpenapiEndpoint(Name alias, Table<OpenapiEndpointRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("openapi能力点"));
    }

    public <O extends Record> OpenapiEndpoint(Table<O> child, ForeignKey<O, OpenapiEndpointRecord> key) {
        super(child, key, OPENAPI_ENDPOINT);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.OPENAPI_ENDPOINT_PRIMARY, Indexes.OPENAPI_ENDPOINT_UNIQ_IDX_UNI_ENDPOINT, Indexes.OPENAPI_ENDPOINT_UNIQ_IDX_UNI_ENDPOINT_NAME);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<OpenapiEndpointRecord, Long> getIdentity() {
        return Keys.IDENTITY_OPENAPI_ENDPOINT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<OpenapiEndpointRecord> getPrimaryKey() {
        return Keys.KEY_OPENAPI_ENDPOINT_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<OpenapiEndpointRecord>> getKeys() {
        return Arrays.<UniqueKey<OpenapiEndpointRecord>>asList(Keys.KEY_OPENAPI_ENDPOINT_PRIMARY, Keys.KEY_OPENAPI_ENDPOINT_UNIQ_IDX_UNI_ENDPOINT, Keys.KEY_OPENAPI_ENDPOINT_UNIQ_IDX_UNI_ENDPOINT_NAME);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OpenapiEndpoint as(String alias) {
        return new OpenapiEndpoint(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OpenapiEndpoint as(Name alias) {
        return new OpenapiEndpoint(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public OpenapiEndpoint rename(String name) {
        return new OpenapiEndpoint(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public OpenapiEndpoint rename(Name name) {
        return new OpenapiEndpoint(name, null);
    }
}
