/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.openapi.tables;


import com.ke.bella.openapi.DefaultSchema;
import com.ke.bella.openapi.Indexes;
import com.ke.bella.openapi.Keys;
import com.ke.bella.openapi.tables.records.OpenapiChannelRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * openapi模型
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OpenapiChannel extends TableImpl<OpenapiChannelRecord> {

    private static final long serialVersionUID = -1015825112;

    /**
     * The reference instance of <code>openapi_channel</code>
     */
    public static final OpenapiChannel OPENAPI_CHANNEL = new OpenapiChannel();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OpenapiChannelRecord> getRecordType() {
        return OpenapiChannelRecord.class;
    }

    /**
     * The column <code>openapi_channel.id</code>. 主键ID
     */
    public final TableField<OpenapiChannelRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "主键ID");

    /**
     * The column <code>openapi_channel.entity_type</code>. 实体类型（endpoint/model）
     */
    public final TableField<OpenapiChannelRecord, String> ENTITY_TYPE = createField("entity_type", org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false).defaultValue(org.jooq.impl.DSL.inline("model", org.jooq.impl.SQLDataType.VARCHAR)), this, "实体类型（endpoint/model）");

    /**
     * The column <code>openapi_channel.entity_code</code>. 实体编码
     */
    public final TableField<OpenapiChannelRecord, String> ENTITY_CODE = createField("entity_code", org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "实体编码");

    /**
     * The column <code>openapi_channel.channel_name</code>. 渠道名称
     */
    public final TableField<OpenapiChannelRecord, String> CHANNEL_NAME = createField("channel_name", org.jooq.impl.SQLDataType.VARCHAR(128).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "渠道名称");

    /**
     * The column <code>openapi_channel.status</code>. 状态状态(active/inactive)
     */
    public final TableField<OpenapiChannelRecord, String> STATUS = createField("status", org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false).defaultValue(org.jooq.impl.DSL.inline("active", org.jooq.impl.SQLDataType.VARCHAR)), this, "状态状态(active/inactive)");

    /**
     * The column <code>openapi_channel.data_destination</code>. 数据流向(inner/mainland/overseas)
     */
    public final TableField<OpenapiChannelRecord, String> DATA_DESTINATION = createField("data_destination", org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false).defaultValue(org.jooq.impl.DSL.inline("inner", org.jooq.impl.SQLDataType.VARCHAR)), this, "数据流向(inner/mainland/overseas)");

    /**
     * The column <code>openapi_channel.priority</code>. 优先级(high/normal/low)
     */
    public final TableField<OpenapiChannelRecord, String> PRIORITY = createField("priority", org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false).defaultValue(org.jooq.impl.DSL.inline("normal", org.jooq.impl.SQLDataType.VARCHAR)), this, "优先级(high/normal/low)");

    /**
     * The column <code>openapi_channel.protocol</code>. 协议
     */
    public final TableField<OpenapiChannelRecord, String> PROTOCOL = createField("protocol", org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "协议");

    /**
     * The column <code>openapi_channel.supplier</code>. 服务商
     */
    public final TableField<OpenapiChannelRecord, String> SUPPLIER = createField("supplier", org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "服务商");

    /**
     * The column <code>openapi_channel.url</code>. 请求通道的url
     */
    public final TableField<OpenapiChannelRecord, String> URL = createField("url", org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "请求通道的url");

    /**
     * The column <code>openapi_channel.channel_info</code>. 渠道信息
     */
    public final TableField<OpenapiChannelRecord, String> CHANNEL_INFO = createField("channel_info", org.jooq.impl.SQLDataType.VARCHAR(512).nullable(false).defaultValue(org.jooq.impl.DSL.inline("{}", org.jooq.impl.SQLDataType.VARCHAR)), this, "渠道信息");

    /**
     * The column <code>openapi_channel.price_info</code>. 单价
     */
    public final TableField<OpenapiChannelRecord, String> PRICE_INFO = createField("price_info", org.jooq.impl.SQLDataType.VARCHAR(256).nullable(false).defaultValue(org.jooq.impl.DSL.inline("{}", org.jooq.impl.SQLDataType.VARCHAR)), this, "单价");

    /**
     * The column <code>openapi_channel.cuid</code>. 创建人id
     */
    public final TableField<OpenapiChannelRecord, Long> CUID = createField("cuid", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.BIGINT)), this, "创建人id");

    /**
     * The column <code>openapi_channel.cu_name</code>. 创建人姓名
     */
    public final TableField<OpenapiChannelRecord, String> CU_NAME = createField("cu_name", org.jooq.impl.SQLDataType.VARCHAR(16).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "创建人姓名");

    /**
     * The column <code>openapi_channel.muid</code>. 编辑人id
     */
    public final TableField<OpenapiChannelRecord, Long> MUID = createField("muid", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.BIGINT)), this, "编辑人id");

    /**
     * The column <code>openapi_channel.mu_name</code>. 编辑人姓名
     */
    public final TableField<OpenapiChannelRecord, String> MU_NAME = createField("mu_name", org.jooq.impl.SQLDataType.VARCHAR(16).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "编辑人姓名");

    /**
     * The column <code>openapi_channel.ctime</code>.
     */
    public final TableField<OpenapiChannelRecord, Timestamp> CTIME = createField("ctime", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>openapi_channel.mtime</code>.
     */
    public final TableField<OpenapiChannelRecord, Timestamp> MTIME = createField("mtime", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>openapi_channel</code> table reference
     */
    public OpenapiChannel() {
        this(DSL.name("openapi_channel"), null);
    }

    /**
     * Create an aliased <code>openapi_channel</code> table reference
     */
    public OpenapiChannel(String alias) {
        this(DSL.name(alias), OPENAPI_CHANNEL);
    }

    /**
     * Create an aliased <code>openapi_channel</code> table reference
     */
    public OpenapiChannel(Name alias) {
        this(alias, OPENAPI_CHANNEL);
    }

    private OpenapiChannel(Name alias, Table<OpenapiChannelRecord> aliased) {
        this(alias, aliased, null);
    }

    private OpenapiChannel(Name alias, Table<OpenapiChannelRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("openapi模型"));
    }

    public <O extends Record> OpenapiChannel(Table<O> child, ForeignKey<O, OpenapiChannelRecord> key) {
        super(child, key, OPENAPI_CHANNEL);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.OPENAPI_CHANNEL_IDX_ENTITY_TYPE_CODE, Indexes.OPENAPI_CHANNEL_IDX_PROTOCOL, Indexes.OPENAPI_CHANNEL_IDX_SUPPLIER, Indexes.OPENAPI_CHANNEL_PRIMARY, Indexes.OPENAPI_CHANNEL_UNIQ_IDX_UNI_CHANNEL_NAME);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<OpenapiChannelRecord, Long> getIdentity() {
        return Keys.IDENTITY_OPENAPI_CHANNEL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<OpenapiChannelRecord> getPrimaryKey() {
        return Keys.KEY_OPENAPI_CHANNEL_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<OpenapiChannelRecord>> getKeys() {
        return Arrays.<UniqueKey<OpenapiChannelRecord>>asList(Keys.KEY_OPENAPI_CHANNEL_PRIMARY, Keys.KEY_OPENAPI_CHANNEL_UNIQ_IDX_UNI_CHANNEL_NAME);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OpenapiChannel as(String alias) {
        return new OpenapiChannel(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OpenapiChannel as(Name alias) {
        return new OpenapiChannel(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public OpenapiChannel rename(String name) {
        return new OpenapiChannel(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public OpenapiChannel rename(Name name) {
        return new OpenapiChannel(name, null);
    }
}
