/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.openapi.tables;


import com.ke.bella.openapi.DefaultSchema;
import com.ke.bella.openapi.Indexes;
import com.ke.bella.openapi.Keys;
import com.ke.bella.openapi.tables.records.OpenapiModelEndpointRelationRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * openapi模型能力点
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OpenapiModelEndpointRelation extends TableImpl<OpenapiModelEndpointRelationRecord> {

    private static final long serialVersionUID = 1534591533;

    /**
     * The reference instance of <code>openapi_model_endpoint_relation</code>
     */
    public static final OpenapiModelEndpointRelation OPENAPI_MODEL_ENDPOINT_RELATION = new OpenapiModelEndpointRelation();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OpenapiModelEndpointRelationRecord> getRecordType() {
        return OpenapiModelEndpointRelationRecord.class;
    }

    /**
     * The column <code>openapi_model_endpoint_relation.id</code>. 主键ID
     */
    public final TableField<OpenapiModelEndpointRelationRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "主键ID");

    /**
     * The column <code>openapi_model_endpoint_relation.model_name</code>. 模型名称
     */
    public final TableField<OpenapiModelEndpointRelationRecord, String> MODEL_NAME = createField("model_name", org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "模型名称");

    /**
     * The column <code>openapi_model_endpoint_relation.endpoint</code>. 请求path
     */
    public final TableField<OpenapiModelEndpointRelationRecord, String> ENDPOINT = createField("endpoint", org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "请求path");

    /**
     * The column <code>openapi_model_endpoint_relation.cuid</code>. 创建人id
     */
    public final TableField<OpenapiModelEndpointRelationRecord, Long> CUID = createField("cuid", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.BIGINT)), this, "创建人id");

    /**
     * The column <code>openapi_model_endpoint_relation.cu_name</code>. 创建人姓名
     */
    public final TableField<OpenapiModelEndpointRelationRecord, String> CU_NAME = createField("cu_name", org.jooq.impl.SQLDataType.VARCHAR(16).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "创建人姓名");

    /**
     * The column <code>openapi_model_endpoint_relation.muid</code>. 编辑人id
     */
    public final TableField<OpenapiModelEndpointRelationRecord, Long> MUID = createField("muid", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.BIGINT)), this, "编辑人id");

    /**
     * The column <code>openapi_model_endpoint_relation.mu_name</code>. 编辑人姓名
     */
    public final TableField<OpenapiModelEndpointRelationRecord, String> MU_NAME = createField("mu_name", org.jooq.impl.SQLDataType.VARCHAR(16).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "编辑人姓名");

    /**
     * The column <code>openapi_model_endpoint_relation.ctime</code>.
     */
    public final TableField<OpenapiModelEndpointRelationRecord, Timestamp> CTIME = createField("ctime", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>openapi_model_endpoint_relation.mtime</code>.
     */
    public final TableField<OpenapiModelEndpointRelationRecord, Timestamp> MTIME = createField("mtime", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>openapi_model_endpoint_relation</code> table reference
     */
    public OpenapiModelEndpointRelation() {
        this(DSL.name("openapi_model_endpoint_relation"), null);
    }

    /**
     * Create an aliased <code>openapi_model_endpoint_relation</code> table reference
     */
    public OpenapiModelEndpointRelation(String alias) {
        this(DSL.name(alias), OPENAPI_MODEL_ENDPOINT_RELATION);
    }

    /**
     * Create an aliased <code>openapi_model_endpoint_relation</code> table reference
     */
    public OpenapiModelEndpointRelation(Name alias) {
        this(alias, OPENAPI_MODEL_ENDPOINT_RELATION);
    }

    private OpenapiModelEndpointRelation(Name alias, Table<OpenapiModelEndpointRelationRecord> aliased) {
        this(alias, aliased, null);
    }

    private OpenapiModelEndpointRelation(Name alias, Table<OpenapiModelEndpointRelationRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("openapi模型能力点"));
    }

    public <O extends Record> OpenapiModelEndpointRelation(Table<O> child, ForeignKey<O, OpenapiModelEndpointRelationRecord> key) {
        super(child, key, OPENAPI_MODEL_ENDPOINT_RELATION);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.OPENAPI_MODEL_ENDPOINT_RELATION_IDX_MODEL_NAME, Indexes.OPENAPI_MODEL_ENDPOINT_RELATION_PRIMARY, Indexes.OPENAPI_MODEL_ENDPOINT_RELATION_UNIQ_IDX_UNI_ENDPOINT_MODEL);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<OpenapiModelEndpointRelationRecord, Long> getIdentity() {
        return Keys.IDENTITY_OPENAPI_MODEL_ENDPOINT_RELATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<OpenapiModelEndpointRelationRecord> getPrimaryKey() {
        return Keys.KEY_OPENAPI_MODEL_ENDPOINT_RELATION_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<OpenapiModelEndpointRelationRecord>> getKeys() {
        return Arrays.<UniqueKey<OpenapiModelEndpointRelationRecord>>asList(Keys.KEY_OPENAPI_MODEL_ENDPOINT_RELATION_PRIMARY, Keys.KEY_OPENAPI_MODEL_ENDPOINT_RELATION_UNIQ_IDX_UNI_ENDPOINT_MODEL);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OpenapiModelEndpointRelation as(String alias) {
        return new OpenapiModelEndpointRelation(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OpenapiModelEndpointRelation as(Name alias) {
        return new OpenapiModelEndpointRelation(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public OpenapiModelEndpointRelation rename(String name) {
        return new OpenapiModelEndpointRelation(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public OpenapiModelEndpointRelation rename(Name name) {
        return new OpenapiModelEndpointRelation(name, null);
    }
}
