/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.openapi.tables;


import com.ke.bella.openapi.DefaultSchema;
import com.ke.bella.openapi.Indexes;
import com.ke.bella.openapi.Keys;
import com.ke.bella.openapi.tables.records.OpenapiEndpointCategoryRelationRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * openapi能力点类目
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OpenapiEndpointCategoryRelation extends TableImpl<OpenapiEndpointCategoryRelationRecord> {

    private static final long serialVersionUID = 54584481;

    /**
     * The reference instance of <code>openapi_endpoint_category_relation</code>
     */
    public static final OpenapiEndpointCategoryRelation OPENAPI_ENDPOINT_CATEGORY_RELATION = new OpenapiEndpointCategoryRelation();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OpenapiEndpointCategoryRelationRecord> getRecordType() {
        return OpenapiEndpointCategoryRelationRecord.class;
    }

    /**
     * The column <code>openapi_endpoint_category_relation.id</code>. 主键ID
     */
    public final TableField<OpenapiEndpointCategoryRelationRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "主键ID");

    /**
     * The column <code>openapi_endpoint_category_relation.endpoint</code>. 能力点
     */
    public final TableField<OpenapiEndpointCategoryRelationRecord, String> ENDPOINT = createField("endpoint", org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "能力点");

    /**
     * The column <code>openapi_endpoint_category_relation.category_code</code>. 类目编码
     */
    public final TableField<OpenapiEndpointCategoryRelationRecord, String> CATEGORY_CODE = createField("category_code", org.jooq.impl.SQLDataType.VARCHAR(128).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "类目编码");

    /**
     * The column <code>openapi_endpoint_category_relation.sort</code>. 排序
     */
    public final TableField<OpenapiEndpointCategoryRelationRecord, Integer> SORT = createField("sort", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "排序");

    /**
     * The column <code>openapi_endpoint_category_relation.cuid</code>. 创建人id
     */
    public final TableField<OpenapiEndpointCategoryRelationRecord, Long> CUID = createField("cuid", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.BIGINT)), this, "创建人id");

    /**
     * The column <code>openapi_endpoint_category_relation.cu_name</code>. 创建人姓名
     */
    public final TableField<OpenapiEndpointCategoryRelationRecord, String> CU_NAME = createField("cu_name", org.jooq.impl.SQLDataType.VARCHAR(16).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "创建人姓名");

    /**
     * The column <code>openapi_endpoint_category_relation.muid</code>. 编辑人id
     */
    public final TableField<OpenapiEndpointCategoryRelationRecord, Long> MUID = createField("muid", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.BIGINT)), this, "编辑人id");

    /**
     * The column <code>openapi_endpoint_category_relation.mu_name</code>. 编辑人姓名
     */
    public final TableField<OpenapiEndpointCategoryRelationRecord, String> MU_NAME = createField("mu_name", org.jooq.impl.SQLDataType.VARCHAR(16).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "编辑人姓名");

    /**
     * The column <code>openapi_endpoint_category_relation.ctime</code>.
     */
    public final TableField<OpenapiEndpointCategoryRelationRecord, Timestamp> CTIME = createField("ctime", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>openapi_endpoint_category_relation.mtime</code>.
     */
    public final TableField<OpenapiEndpointCategoryRelationRecord, Timestamp> MTIME = createField("mtime", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>openapi_endpoint_category_relation</code> table reference
     */
    public OpenapiEndpointCategoryRelation() {
        this(DSL.name("openapi_endpoint_category_relation"), null);
    }

    /**
     * Create an aliased <code>openapi_endpoint_category_relation</code> table reference
     */
    public OpenapiEndpointCategoryRelation(String alias) {
        this(DSL.name(alias), OPENAPI_ENDPOINT_CATEGORY_RELATION);
    }

    /**
     * Create an aliased <code>openapi_endpoint_category_relation</code> table reference
     */
    public OpenapiEndpointCategoryRelation(Name alias) {
        this(alias, OPENAPI_ENDPOINT_CATEGORY_RELATION);
    }

    private OpenapiEndpointCategoryRelation(Name alias, Table<OpenapiEndpointCategoryRelationRecord> aliased) {
        this(alias, aliased, null);
    }

    private OpenapiEndpointCategoryRelation(Name alias, Table<OpenapiEndpointCategoryRelationRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("openapi能力点类目"));
    }

    public <O extends Record> OpenapiEndpointCategoryRelation(Table<O> child, ForeignKey<O, OpenapiEndpointCategoryRelationRecord> key) {
        super(child, key, OPENAPI_ENDPOINT_CATEGORY_RELATION);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.OPENAPI_ENDPOINT_CATEGORY_RELATION_IDX_CATEGORY_CODE, Indexes.OPENAPI_ENDPOINT_CATEGORY_RELATION_IDX_SORT, Indexes.OPENAPI_ENDPOINT_CATEGORY_RELATION_PRIMARY, Indexes.OPENAPI_ENDPOINT_CATEGORY_RELATION_UNIQ_IDX_UNI_ENDPOINT_CATEGORY_CODE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<OpenapiEndpointCategoryRelationRecord, Long> getIdentity() {
        return Keys.IDENTITY_OPENAPI_ENDPOINT_CATEGORY_RELATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<OpenapiEndpointCategoryRelationRecord> getPrimaryKey() {
        return Keys.KEY_OPENAPI_ENDPOINT_CATEGORY_RELATION_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<OpenapiEndpointCategoryRelationRecord>> getKeys() {
        return Arrays.<UniqueKey<OpenapiEndpointCategoryRelationRecord>>asList(Keys.KEY_OPENAPI_ENDPOINT_CATEGORY_RELATION_PRIMARY, Keys.KEY_OPENAPI_ENDPOINT_CATEGORY_RELATION_UNIQ_IDX_UNI_ENDPOINT_CATEGORY_CODE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OpenapiEndpointCategoryRelation as(String alias) {
        return new OpenapiEndpointCategoryRelation(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OpenapiEndpointCategoryRelation as(Name alias) {
        return new OpenapiEndpointCategoryRelation(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public OpenapiEndpointCategoryRelation rename(String name) {
        return new OpenapiEndpointCategoryRelation(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public OpenapiEndpointCategoryRelation rename(Name name) {
        return new OpenapiEndpointCategoryRelation(name, null);
    }
}
