name: Create Release Tag

on:
  push:
    branches:
      - main

jobs:
  create-release-tag:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 获取所有历史记录和标签
      
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: 'maven'
      
      - name: Calculate next version
        id: calc-version
        run: |
          # 获取 POM 版本
          cd api
          POM_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "POM version: $POM_VERSION"
          
          # 检查是否为 SNAPSHOT 版本
          if [[ "$POM_VERSION" == *-SNAPSHOT* ]]; then
            echo " POM version ($POM_VERSION) is a SNAPSHOT version"
            echo "::error::POM version cannot be a SNAPSHOT version for release. Please use a release version."
            exit 1
          fi
          
          # 获取最新的版本标签
          git fetch --tags
          LATEST_TAG=$(git tag -l "v*" | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | sort -V | tail -n 1)
          
          if [ -z "$LATEST_TAG" ]; then
            # 如果没有找到标签，使用 POM 版本创建第一个标签
            NEXT_TAG="v$POM_VERSION"
            echo "No existing version tags found. Using POM version: $NEXT_TAG"
          else
            echo "Latest tag: $LATEST_TAG"
            TAG_VERSION=${LATEST_TAG#v}
            
            # 比较 POM 版本和标签版本
            if [ "$(printf '%s\n' "$TAG_VERSION" "$POM_VERSION" | sort -V | head -n1)" != "$POM_VERSION" ]; then
              # 如果 POM 版本大于标签版本，使用 POM 版本
              NEXT_TAG="v$POM_VERSION"
              echo "POM version ($POM_VERSION) is greater than tag version ($TAG_VERSION). Using POM version for new tag: $NEXT_TAG"
            else
              # 否则增加补丁版本号
              IFS='.' read -r MAJOR MINOR PATCH <<< "$TAG_VERSION"
              PATCH=$((PATCH + 1))
              NEXT_TAG="v$MAJOR.$MINOR.$PATCH"
              echo "POM version ($POM_VERSION) is not greater than tag version ($TAG_VERSION). Incrementing patch version to $NEXT_TAG"
            fi
          fi
          
          # 设置输出变量
          echo "version=$NEXT_TAG" >> $GITHUB_OUTPUT
      
      - name: Create and push tag
        id: create-tag
        run: |
          TAG=${{ steps.calc-version.outputs.version }}
          
          # 配置 Git
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          
          # 创建带注释的标签
          git tag -a $TAG -m "Release $TAG"
          
          # 推送标签
          git push origin $TAG
          
          echo "Created and pushed tag: $TAG"